### ISSUE TITLE
Docs: Update 'Style Guide for Pull Requests' in CONTRIBUTING.md

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#101]
## Category

- [x] Documentation
- [ ] Resource Addition

## Description

We need to update 'Style Guide for Pull Requests' in CONTRIBUTING.md by replacing the current markdown with the suggested markdown.

Current Markdown:

> There can be three types of PRs for this repository:

Suggested Markdown:

> There can be four types of PRs for this repository:

**Comment by Kombaiya-MK** [comment]
Hi @Sriparno08 Can I work on this issue?

**Comment by Sriparno08** [comment]
Sure 👍
