### ISSUE TITLE
Docs: Add ‘Style Guide for Pull Requests’ Under ‘Table of Contents’ in CONTRIBUTING.md

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#102]
## Category

- [x] Documentation
- [ ] Resource Addition

## Description

We need to add ‘Style Guide for Pull Requests’ under ‘Table of Contents’ in CONTRIBUTING.md.

Suggested Markdown:

```
- [Issues](#issues)
- [Pull Requests](#pull-requests)
- [Making a Pull Request](#making-a-pull-request)
- [Style Guide for Commit Messages](#style-guide-for-commit-messages)
- [Style Guide for Pull Requests](#style-guide-for-pull-requests)
```

**Comment by maryjonah** [comment]
@Sriparno08 I have submitted a [PR: 103](https://github.com/Sriparno08/Openpedia/pull/103) for this issue
