### ISSUE TITLE
Docs: Add 'Tech Stack' Under 'Table of Contents' in README.md

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#106]
## Category

- [x] Documentation
- [ ] Resource Addition

## Description

We need to add ‘Tech Stack’ under ‘Table of Contents’ in README.md.

Suggested Markdown:

```
- [Introduction to Open Source](#-introduction-to-open-source)
- [Learn Git and GitHub](#-learn-git-and-github)
- [Contributing to Open Source](#-contributing-to-open-source)
- [Beginner-Friendly Repos](#-beginner-friendly-repos)
- [Open Source Programs](#-open-source-programs)
- [Tech Stack](#-tech-stack)
- [Contributing](#-contributing)
- [License](#-license)
```

**Comment by Shivamk034** [comment]
I'm interested in working on this issue. Can it be assigned to me?

**Comment by Sriparno08** [comment]
Sure 👍

**Comment by Shivamk034** [comment]
@Sriparno08 , thank you for assigning this issue to me. I've made the necessary changes to address the issue. Could you please review my pull request whenever you have the time? Your feedback will be greatly appreciated!

**Comment by Sriparno08** [comment]
You're welcome, @Shivamk034 👍
