### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by prasukjain07** [Sriparno08/Openpedia#108]
The Navbar can be improve, also the logo on Navbar. The main body also can be modify, please assign this issue to me

**Comment by camilo-zuluaga** [comment]
Hey @prasukjain07 , from.my point of view, it will be better if u explain what changes specifically would u do, how and why to get a better understanding of this issue 👍

**Comment by Sriparno08** [comment]
+1 to what @camilo-zuluaga said 👍

**Comment by prasukjain07** [comment]
We can change the logo of Openpedia, and add contacts option, about button is not working properly, and instead of giving it dark shade, just make it white and change color and shapes of buttons to make it more attractive, also we can add faqs page in application and make a button for it on navbar

**Comment by Sriparno08** [comment]
Thanks for suggesting these interesting ideas, @prasukjain07 👍

Before we move on to implementing them, we will analyze if they fit this project and open issues according to that. Then, you can ask to get assigned to those issues.

Also, are you participating in JGEC Winter of Code (JWoC)?

**Comment by prasukjain07** [comment]
Yes I am participating in JWoC

**Comment by Sriparno08** [comment]
Okay, then stay tuned for the issues.

I'm closing this one as it needs to be separated into multiple issues.
