### ISSUE TITLE
Links not working in the Categories part

### ISSUE THREAD

**Issue by thesri** [Sriparno08/Openpedia#110]
## Category

- [ ] Documentation
- [ ] Resource Addition

## Description

The links in the categories section needs to be improved. 
![Screenshot 2024-01-11 112545](https://github.com/Sriparno08/Openpedia/assets/98333833/98418462-db6f-45ca-9750-df6126ebdec9)
they are showing error. 
please kindly assign this issue to me. under JWOC 2024

**Comment by Sriparno08** [comment]
The links are not working because the pages are yet to be made by contributors like you! 😄

Once they are made, we'll open an issue on this exact topic and then, you can ask to get assigned to it.

For now, we're closing this issue.
