### ISSUE TITLE
Pages not made in the categories section 

### ISSUE THREAD

**Issue by thesri** [Sriparno08/Openpedia#111]
## Category

- [ ] Documentation
- [ ] Resource Addition

## Description

There are some pages to be made, if i can contribute to it please assign this issue to me

**Comment by Sriparno08** [comment]
Hey @thesri, I'll open an issue for each page soon where you can ask to get assigned and hence, I'm closing this one.

Also, as the JWoC website suggests, the first coding period starts on 15th Jan, 2024. So, the issues can only be assigned and you can only start working on an issue from 15th Jan. So, hold on for a few days and you can then start working at full force.
