### ISSUE TITLE
UI: Remove Notification From Landing Page

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#114]
## Description

We need to remove the following notification from the landing page:

<p align="center">
  <img src="https://github.com/Sriparno08/Openpedia/assets/89148144/8c42c2cf-937f-4fbe-afe9-d0eb69ac646e">
</p>

**For Assignee:**

> Ensure that you submit a PR for this issue within 1 day. Otherwise, you will be unassigned from this issue and it will be passed on to the next contributor who asked to be assigned to it.

_Note: This issue is for JWoC 2024 participants. If you are not participating in this event, please refrain from asking to get assigned to this issue._

**Comment by zul132** [comment]
@Sriparno08 hey I am interested in working on this issue. Please assign it to me after Jan 15th

**Comment by ayesha-2101** [comment]
@Sriparno08 I am interested in contributing to this as a part of JWOC. Please assign it to me.

**Comment by thatguywhocode** [comment]
hey @Sriparno08 , I would like to contribute my part in this error, kindly assign it to me under JWOC'24.Thank You

**Comment by Divyanshgarg-04** [comment]
@Sriparno08 I am interested in resolving this issue please assign this to me under JWOC

**Comment by Anushkabh** [comment]
@Sriparno08  i would like to work on this. kindly assign under JWOC

**Comment by thatguywhocode** [comment]
Hello @Sriparno08   , I would like to work on this issue under JWOC.

**Comment by Sriparno08** [comment]
Hey @Anushkabh, you're assigned 👍

**Comment by hittie45** [comment]
Hello @Sriparno08 I would like to work on this issue under JWOC

**Comment by Anushkabh** [comment]
@Sriparno08  kindly merge the PR if satisfied. #145
