### ISSUE TITLE
Feat: Add Footer Section

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#115]
## Description

We need to add a footer section to the landing page.

**For Assignee:**

> Ensure that you submit a PR for this issue within 3 days. Otherwise, you will be unassigned from this issue and it will be passed on to the next contributor who asked to be assigned to it.

_Note: This issue is for JWoC 2024 participants. If you are not participating in this event, please refrain from asking to get assigned to this issue._

**Comment by Sriparno08** [comment]
Hey @NaveenChandraAdhikari, since you suggested this idea, do you want to get assigned to this issue once the first coding period starts?

**Comment by Ananyamishra08** [comment]
i am interested Please assign me

**Comment by NaveenChandraAdhikari** [comment]
Definitely 😊

**Comment by Sriparno08** [comment]
Great 👍

**Comment by Ananyamishra08** [comment]
hello @Sriparno08 pls assign this to me

**Comment by Sriparno08** [comment]
Hey @NaveenChandraAdhikari, requests made before 15th Jan, 2024 are not considered for assignment. You have to make one on or after 15th Jan, 2024 with the 'JWOC' keyword in your comment to be considered.

Hey @Ananyamishra08, you haven't included the 'JWOC' keyword in your comment.

The one who ticks all the boxes first will be assigned to this issue.

**Comment by zul132** [comment]
@Sriparno08 I would like to work on this issue under JWOC. Kindly assign it to me

**Comment by Ananyamishra08** [comment]
hey @Sriparno08 i am sorry for the mistake .Can u reassign me this issue under JWOC

**Comment by Sriparno08** [comment]
Hey @Ananyamishra08, you're assigned 👍

To Others:

The mentee who is assigned to this issue is chosen because he/she was the first one to ask for assignment on or after 15th Jan, 2024 with the 'JWOC' keyword in his/her comment.

Hey @zul132, you're already assigned to another issue. So, you will not be considered for this one.

**Comment by NaveenChandraAdhikari** [comment]
Hey @NaveenChandraAdhikari, since you suggested this idea, do you want to get assigned to this issue once the first coding period starts? 
@Sriparno08 that is something you have said

**Comment by Sriparno08** [comment]
Correctly said, @NaveenChandraAdhikari.

But as the organizers notified, any comments made before 15th Jan, 2024 should not be considered for assignment. So unfortunately, all the mentors who have kept issues on hold for assignment to a particular mentee had to make them open for everyone.

Sorry for the inconvenience caused as the mentors were notified about it just before the first coding period starts.

**Comment by amanswarnakar** [comment]
@Sriparno08 please assign this issue to me under JWOC'24.
