### ISSUE TITLE
Feat: Create an 'Introduction to Open Source' Page

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#116]
## Description

We need to create an 'Introduction to Open Source' page:

- Keep the theme intact
- Add some placeholder entries to the page as resources as the real ones will be dynamically inserted later
- The way in which each resource will show up is up to you

**For Assignee:**

> Ensure that you submit a PR for this issue within 4 days. Otherwise, you will be unassigned from this issue and it will be passed on to the next contributor who asked to be assigned to it.

_Note: This issue is for JWoC 2024 participants. If you are not participating in this event, please refrain from asking to get assigned to this issue._

**Comment by zul132** [comment]
@Sriparno08 I am interested in working on this issue. Kindly assign it to me on/after Jan 15th

**Comment by Ananyamishra08** [comment]
Hello, @Sriparno08 I would like to work on this , please assign it to me.

**Comment by sanjayh-2022** [comment]
I would like work on this ,please assign it to me JWOC

**Comment by zul132** [comment]
> @Sriparno08 I am interested in working on this issue. Kindly assign it to me on/after Jan 15th

I would like to work on this issue under JWoC. Please assign it to me @Sriparno08

**Comment by Sriparno08** [comment]
Hey @sanjayh-2022, you're assigned 👍

To Others:

The mentee who is assigned to this issue is chosen because he/she was the first one to ask for assignment on or after 15th Jan, 2024 with the 'JWOC' keyword in his/her comment.

**Comment by Surajit0573** [comment]
Hi, @Sriparno08, It has been 5 days since this issue was assigned. and the time limit for a hard issue was 4 days...so please re-assign this to me under 2024...I worked on your project before and I can complete this issue in time.

**Comment by Sriparno08** [comment]
Hey @sanjayh-2022, please submit a PR for this issue as soon as possible. If not, you will be unassigned from this issue.

Hey @Ananyamishra08, @zul132 and @Surajit0573, please make a fresh comment with the 'JWOC' (Case-Sensitive) keyword in your comment to be considered for assignment.

The first one to do it will be assigned if @sanjayh-2022 doesn't respond with a PR soon.

**Comment by Surajit0573** [comment]
> Hey @sanjayh-2022, please submit a PR for this issue as soon as possible. If not, you will be unassigned from this issue.
> 
> Hey @Ananyamishra08, @zul132 and @Surajit0573, please make a fresh comment with the 'JWOC' (Case-Sensitive) keyword in your comment to be considered for assignment.
> 
> The first one to do it will be assigned if @sanjayh-2022 doesn't respond with a PR soon.

Please assign me in this issue under JWOC 2024, if not completed

**Comment by Ananyamishra08** [comment]
Pls assign this issue under jwoc to me

**Comment by zul132** [comment]
Please assign this issue to me under JWOC, if not completed.

**Comment by Sriparno08** [comment]
Hey @Surajit0573, you're assigned.

To Others:

The mentee who is assigned to this issue is chosen because he/she was the first one to ask for assignment with the 'JWOC' keyword in his/her comment.
