### ISSUE TITLE
Chore: Change 'About' Description in Landing Page

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#126]
## Description

We need to change the 'About' section description in landing page by replacing the current one with the following one:

> Openpedia offers a large amount of useful resources that enable you to become a seasoned open source contributor. If you are aspiring to leave your imprint in the world of open source, then this website is an excellent fit for you.

**For Assignee:**

> Ensure that you submit a PR for this issue within 1 day. Otherwise, you will be unassigned from this issue and it will be passed on to the next contributor who asked to be assigned to it.

_Note: This issue is for JWoC 2024 participants. If you are not participating in this event, please refrain from asking to get assigned to this issue._

**Comment by sanskritisahu21** [comment]
I'm interested in working on this issue. Please assign this issue to me.

**Comment by Aswinr24** [comment]
Would like to work on this issue, Hoping to be assigned to do it once the coding period starts

**Comment by SGCODEX** [comment]
I want to work on this under JWOC

**Comment by singhcodes26** [comment]
would like to work on this issue

**Comment by Ananyamishra08** [comment]
Hello, @Sriparno08 I would like to work on this , please assign it to me.

**Comment by sanskritisahu21** [comment]
I would like to work on this issue under JWOC. Please assign this to me.

**Comment by Sriparno08** [comment]
Hey @sanskritisahu21, you're assigned 👍

To Others:

The mentee who is assigned to this issue is chosen because he/she was the first one to ask for assignment on or after 15th Jan, 2024 with the 'JWOC' keyword in his/her comment.
