### ISSUE TITLE
Chore: Change 'Contribute' Description in Landing Page

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#127]
## Description

We need to change the 'Contribute' section description in landing page by replacing the current one with the following one:

> Openpedia is waiting for your contribution! There are many ways that you can contribute to this project, such as improving the documentation, adding resources, enhancing the codebase and more.

**For Assignee:**

> Ensure that you submit a PR for this issue within 1 day. Otherwise, you will be unassigned from this issue and it will be passed on to the next contributor who asked to be assigned to it.

_Note: This issue is for JWoC 2024 participants. If you are not participating in this event, please refrain from asking to get assigned to this issue._

**Comment by sanskritisahu21** [comment]
I'm interested in working on this issue. Please assign this issue to me.

**Comment by Ananyamishra08** [comment]
Hello, @Sriparno08  , Please assign me this issue.I am eager to work on this

**Comment by Aswinr24** [comment]
Hey would like to work on this issue, Please do assign this to me once the period starts

**Comment by ayesha-2101** [comment]
@Sriparno08 I am interested in contributing to this as a part of JWOC. Please assign it to me.

**Comment by Ananyamishra08** [comment]
Hello, @Sriparno08 I would like to work on this , please assign it to me.

**Comment by ShreyaTiwari05** [comment]
Hii, I am willing to contribute in this issue under JWoC'24

**Comment by thesri** [comment]
hey @Sriparno08  i am willing to contribute to this issue

**Comment by sanskritisahu21** [comment]
I would like to work on this issue under JWOC. Please assign this issue to me.

**Comment by Isha1031** [comment]
I want to work on this issue under JWOC

**Comment by Sriparno08** [comment]
Hey @Isha1031, you're assigned 👍

To Others:

The mentee who is assigned to this issue is chosen because he/she was the first one to ask for assignment on or after 15th Jan, 2024 with the 'JWOC' (Case-Sensitive) keyword in his/her comment.

Hey @sanskritisahu21, you're already assigned to another issue. So, you will not be considered for this one.

**Comment by Isha1031** [comment]
sir, what changes do I have to make on this page?

**Comment by Sriparno08** [comment]
Here you go:

1. Go to client/index.html
2. Find the description for the 'Contribute' section on the landing page
3. Change the description with the one suggested in the issue

**Comment by antilneeraj** [comment]
@Sriparno08 I would like to work on this issue as soon as my PR gets approved kindly assign this issue to me under JWOC.

**Comment by Sriparno08** [comment]
Hey @antilneeraj, another mentee @Isha1031 is already assigned to this issue.

**Comment by sanskritisahu21** [comment]
> Here you go:
> 
> 1. Go to client/index.html
> 2. Find the description for the 'Contribute' section on the landing page
> 3. Change the description with the one suggested in the issue

Do I need to do the same for issue #126, which is assigned to me?
