### ISSUE TITLE
Docs: Change 'Contributing' Description in README.md

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#129]
## Category

- [x] Documentation
- [ ] Resource Addition

## Description

We need to change the 'Contribute' section description in landing page by replacing the current one with the following one:

> Openpedia is waiting for your contribution!
>
>There are many ways that you can contribute to this project, such as improving the documentation, adding resources, enhancing the codebase and more.
>
> Please go through the [CONTRIBUTING](https://github.com/Sriparno08/Openpedia/blob/main/CONTRIBUTING.md) guide for details.

**Comment by zul132** [comment]
hey @Sriparno08 please assign this issue to me (once the Coding phase starts)
