### ISSUE TITLE
Feat: Create an 'Open Source Programs' Page

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#131]
## Description

We need to create an 'Open Source Programs' page that displays a range of open source programs that exist on the internet.

Guidelines:

- Keep the theme intact
- Add some placeholder entries as resources as the real ones will be dynamically inserted later
- The structure of the page depends on you

**For Assignee:**

> Ensure that you submit a PR for this issue within 4 days. Otherwise, you will be unassigned from this issue and it will be passed on to the next contributor who asked to be assigned to it.

_Note: This issue is for JWoC 2024 participants. If you are not participating in this event, please refrain from asking to get assigned to this issue._

**Comment by Sriparno08** [comment]
Hey @Surajit0573, do you want to get assigned to this issue once the first coding period starts?

**Comment by Surajit0573** [comment]
Yes!!...please.

**Comment by Sriparno08** [comment]
Great 👍

Then, I'll assign you on or after 15th Jan, 2024.

**Comment by Surajit0573** [comment]
Please assign me this issue under JWOC 2024

**Comment by sanjayh-2022** [comment]
I would like to contribute to this project JWOC

**Comment by Sriparno08** [comment]
Hey @Surajit0573, you're assigned 👍

Hey @sanjayh-2022, you're already assigned to another issue. So, you will not be considered for this one.
