### ISSUE TITLE
Feat: Create a FAQ Page

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#132]
## Description

We need to create a FAQ page that answers a variety of questions regarding the project.

Guidelines:

- Keep the theme intact
- The structure of the page depends on you
- The questions and the answers should be inserted to the best of your logical ability

**For Assignee:**

> Ensure that you submit a PR for this issue within 4 days. Otherwise, you will be unassigned from this issue and it will be passed on to the next contributor who asked to be assigned to it.

_Note: This issue is for JWoC 2024 participants. If you are not participating in this event, please refrain from asking to get assigned to this issue._

**Comment by antilneeraj** [comment]
I'm interested in contributing and would like to work on this issue. I've reviewed the guidelines and am committed to following them. Can you please assign this issue to me?

**Comment by Sriparno08** [comment]
Sure 👍

**Comment by Aswinr24** [comment]
Would like to work on this issue

**Comment by antilneeraj** [comment]
> Sure 👍

I would like to work on this issue and with updated server guidelines I request you again to assign this issue to me under **JWOC**

**Comment by thesri** [comment]
hey @Sriparno08  i am willing to contribute to this issue

**Comment by Sriparno08** [comment]
Hey @antilneeraj, you need to comment again with the 'JWOC' keyword in your comment as the current one was before 15th Jan, 2024.

Hey @thesri, you haven't included the 'JWOC' keyword in your comment.

The first one to tick all the boxes gets assigned to this issue.

**Comment by antilneeraj** [comment]
>I would like to work on this issue and with updated server guidelines I request you again to assign this issue to me under JWOC

Hey @Sriparno08 I have already commented above at exactly 12:00 am with the keyword JWOC

**Comment by antilneeraj** [comment]
@Sriparno08 I would like to work on this issue and with updated server guidelines I request you again to assign this issue to me under **JWOC**

Checklist -

- [x] Responsive Design
- [x] Themed Integration
- [x] Relevant FAQ Questions
- [x] Proper Routing of FAQ Page

**Comment by Sriparno08** [comment]
> Hey @Sriparno08 I have already commented above at exactly 12:00 am with the keyword JWOC. You can check the Discord Channel of openpedia I've commented there also.

Correct, @antilneeraj 👍

But for some reason, it shows 11:59 pm on your comment. Since this event has a tracker which is tracking all these details, we shouldn't take any risk regarding this as it can make your assignment a non-considerable one.

So, to keep you on the safe side, I suggested you to comment again on this issue.

**Comment by Sriparno08** [comment]
Your idea looks great 👍

So, I've assigned it to you.

**Comment by antilneeraj** [comment]
@Sriparno08 Thankyou

**Comment by Sriparno08** [comment]
@antilneeraj You're welcome 😄
