### ISSUE TITLE
FIX: Get Started button.

### ISSUE THREAD

**Issue by Ashutosh104** [Sriparno08/Openpedia#134]
- [x] Documentation
- [x] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

## Description
The "Get started button" should be more attractive and stylish. Iam in JWOC 2024

![img](https://github.com/Sriparno08/Openpedia/assets/143163927/70d4a70d-c0e1-416e-bd78-10715f698032)

**Comment by Sriparno08** [comment]
Hey @Ashutosh104, mentees can't open issues before 15th Jan, 2024. So, I'll have to close this one.

Please open a fresh issue on this exact topic on or after 15th Jan, 2024. Once opened, I'll assign it to you.
