### ISSUE TITLE
[FIX]: Nav bar and get started button styling

### ISSUE THREAD

**Issue by Ashutosh104** [Sriparno08/Openpedia#136]
## Category

- [x] Documentation
- [x] User Interface
-

## Description

The Nav bar and the get started button should be more appealing and attractive. JWOC

![img](https://github.com/Sriparno08/Openpedia/assets/143163927/a724a64a-aad2-4609-af4c-457af33dd294)

**Comment by TejaswaniVelugoti** [comment]
I am interested in contributing to this as a part of JWOC. Please assign it to me.

**Comment by prasukjain07** [comment]
Hey mentor, please assign this issue to me under JWoC

**Comment by Sriparno08** [comment]
Hey @Ashutosh104 & @prasukjain07, you haven't included the 'JWOC' (Case-Sensitive) keyword in your comment.

The first one to tick all the boxes gets assigned to this issue.

**Comment by zul132** [comment]
I am interested in working on this issue under JWOC. Kindly assign it to me

**Comment by Sriparno08** [comment]
Hey @zul132, you're assigned 👍

To Others:

The mentee who is assigned to this issue is chosen because he/she was the first one to ask for assignment on or after 15th Jan, 2024 with the 'JWOC' (Case-Sensitive) keyword in his/her comment.

**Comment by zul132** [comment]
Thank you @Sriparno08
