### ISSUE TITLE
FEAT: Adding banner page and adjustments in UI

### ISSUE THREAD

**Issue by Abhishek-465** [Sriparno08/Openpedia#138]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

## Description
I want to add a relevant banner page with the texts intact in the home page of the website and also add required border radii for a better UI.

![Screenshot (73)](https://github.com/Sriparno08/Openpedia/assets/127030695/b7a1ea75-5a2d-434a-80f3-7027bfaca83f)

Kindly assign me the issue.
I am contributing under JWOC.

**Comment by Sriparno08** [comment]
Hey @Abhishek-465, what do you mean by banner page?

Please explain it or show a little demo to make it visually understandable.

**Comment by Abhishek-465** [comment]
Sorry it was a typo. I meant banner image. The space is vacant ,only have banner texts. I want to add a relevant background-image in that space and also implement border radii in the boxes of experience  section.

**Comment by Sriparno08** [comment]
Got it and sounds good 👍

I'm assigning this issue to you.
