### ISSUE TITLE
Docs: Want to add a new Video under the Learning git and github section

### ISSUE THREAD

**Issue by zul132** [Sriparno08/Openpedia#139]
## Category

- [ ] Documentation
- [x] Resource Addition
- [ ] Codebase
- [ ] User Interface
- [ ] Feature Request

**Comment by zul132** [comment]
@Sriparno08 I want to work on this issue under JWoC. Kindly assign it to me

**Comment by zul132** [comment]
@Sriparno08 Also please kindly add the label for the difficulty level of this issue

**Comment by Sriparno08** [comment]
Hey @zul132, documentation improvements are not considered as valid contributions for this event.

Once the corresponding pages are made with the actual data, you will be able to add new resources to the website.

So, keep an eye on the website and open an issue as soon as the changes are implemented. In case of this issue, I'm closing it as the discussion is now done.
