### ISSUE TITLE
[Feature]: Adding a back to top button in home page

### ISSUE THREAD

**Issue by NaveenChandraAdhikari** [Sriparno08/Openpedia#140]
## Category

- [X] Codebase
- [X] User Interface
- [X] Feature Request

## Description
For better UI enhancement i want to add back to top button in home page 

JWOC2k24

**Comment by Sriparno08** [comment]
Good idea, @NaveenChandraAdhikari 👍

Please mention 'JWOC' in your comment to get considered for assignment.

**Comment by antilneeraj** [comment]
@Sriparno08 I would like to work on this issue and request you to assign this issue to me under **JWOC**

**Comment by Sriparno08** [comment]
Hey @antilneeraj, you have a PR waiting to be merged. Once it's merged, you will be considered for another issue.

**Comment by Sriparno08** [comment]
Hey @NaveenChandraAdhikari, you're assigned 👍

**Comment by antilneeraj** [comment]
Alright!

**Comment by Aswinr24** [comment]
Hey would like to work on this issue under JWOC 24

**Comment by Sriparno08** [comment]
Hey @Aswinr24, another mentee @NaveenChandraAdhikari is already assigned to this issue.

**Comment by PushkarRai04** [comment]
Hey I would like to work on this issue under JWOC

**Comment by this-is-yaash** [comment]
If this issue is available 
I would like to work on it **JWOC**
