### ISSUE TITLE
Feat: Update Navbar UI & Add Custom Scrollbar

### ISSUE THREAD

**Issue by antilneeraj** [Sriparno08/Openpedia#146]
## Category

- [x] Codebase
- [x] User Interface Enhancements
- [x] Feature Request

## Description

I would like to update the UI of navbar. I intend to make the navbar sticky, enhance it with features such as box-shadow, improved text styles, hover effects and other Modern UI trends. Additionally, I would like to incorporate a custom scrollbar into the website.

- Modern UI such as:
Until someone scrolls on the website, the navbar's background will remain transparent with a border. Upon scrolling, it will become sticky, and its appearance will be filled with a theme color & backdrop blur effect.

Can you please assign this issue to me under JWOC.

**Comment by antilneeraj** [comment]
@Sriparno08 Please set the necessary labels and kindly assign this issue to me under JWOC.

**Comment by Sriparno08** [comment]
The idea around the navbar UI sounds good and you can implement it. But for now, we'll continue with the original scrollbar.

I'm assigning this issue to you.
