### ISSUE TITLE
FEAT: Adding dark mode with toggle feature

### ISSUE THREAD

**Issue by Abhishek-465** [Sriparno08/Openpedia#149]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [x] Feature Request

## Description
I want to  add dark mode with toggle feature.
Kindly assign me.
Contributing under JWOC.

**Comment by Sriparno08** [comment]
You're assigned 👍

**Comment by Sriparno08** [comment]
Hey @Abhishek-465, please submit a PR for this issue as soon as possible. If not, you will be unassigned from this issue.

**Comment by Abhishek-465** [comment]
@Sriparno08 I have made the PR. Thank you.
