### ISSUE TITLE
UI: Remove Notification From the FAQ Page

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#151]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

## Description

We need to remove the following notification from the FAQ page:

<p align="center">
  <img src="https://github.com/Sriparno08/Openpedia/assets/89148144/8c42c2cf-937f-4fbe-afe9-d0eb69ac646e">
</p>

**For Assignee:**

> Ensure that you submit a PR for this issue within 1 day. Otherwise, you will be unassigned from this issue and it will be passed on to the next contributor who asked to be assigned to it.

_Note: This issue is for JWoC 2024 participants. If you are not participating in this event, please refrain from asking to get assigned to this issue._

**Comment by Hritikraj8804** [comment]
I'm interested in working on this issue. Please assign this issue to me.

**Comment by Hritikraj8804** [comment]
I'm interested in working on this issue. Please assign this issue to me under JWOC.

**Comment by AftabMankapure** [comment]
Assign me under jwoc

**Comment by Sriparno08** [comment]
Hey @Hritikraj8804, you're assigned 👍

To Others:

The mentee who is assigned to this issue is chosen because he/she was the first one to ask for assignment on or after 15th Jan, 2024 with the 'JWOC' keyword in his/her comment.
