### ISSUE TITLE
UI: Update the Navbar on the FAQ Page

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#152]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

## Description

We need to update the navbar on the FAQ Page by making it look exactly like the navbar on the landing page.

**For Assignee:**

> Ensure that you submit a PR for this issue within 1 day. Otherwise, you will be unassigned from this issue and it will be passed on to the next contributor who asked to be assigned to it.

_Note: This issue is for JWoC 2024 participants. If you are not participating in this event, please refrain from asking to get assigned to this issue._

**Comment by AftabMankapure** [comment]
Assign me under JWoC

**Comment by Sriparno08** [comment]
Hey @AftabMankapure, please mention the 'JWOC' (Case-Sensitive) keyword in your comment to be considered for assignment.

**Comment by akarshi19** [comment]
Please assign me this issue under JWOC'24

**Comment by Divyanshgarg-04** [comment]
@Sriparno08 Can you assign this issue to me now under JWOC

**Comment by Sriparno08** [comment]
Hey @Divyanshgarg-04, you're assigned.

To Others:

The mentee who is assigned to this issue is chosen because he/she was the first one to ask for assignment on or after 15th Jan, 2024 with the 'JWOC' (Case-Sensitive) keyword in his/her comment.
