### ISSUE TITLE
Chore: Change Footer Text in FAQ Page

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#153]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [x] Codebase
- [ ] User Interface
- [ ] Feature Request

## Description

We need to change the footer text in the FAQ page by replacing the current one with the following one:

> Developed By Sriparno Roy & Open Source Community

**For Assignee:**

> Ensure that you submit a PR for this issue within 1 day. Otherwise, you will be unassigned from this issue and it will be passed on to the next contributor who asked to be assigned to it.

_Note: This issue is for JWoC 2024 participants. If you are not participating in this event, please refrain from asking to get assigned to this issue._

**Comment by AftabMankapure** [comment]
Assign me under jwoc

**Comment by Divyanshgarg-04** [comment]
@Sriparno08 I would love to work on this issue under JWOC. Please assign this issue to me

**Comment by akarshi19** [comment]
I would love to work on this issue under JWOC. Please assign this issue to me

**Comment by swetasingh8844** [comment]
@Sriparno08 please assign this issue to me under JWOC'24
