### ISSUE TITLE
UI: Update Top Navbar in 'Open Source Programs' Page

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#154]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

## Description

We need to update the top navbar in 'Open Source Programs' page by replacing the current one with the one in the landing page:

![image](https://github.com/Sriparno08/Openpedia/assets/89148144/b4b413f6-9649-448a-b4c8-2dcc94d90325)

**For Assignee:**

> Ensure that you submit a PR for this issue within 1 day. Otherwise, you will be unassigned from this issue and it will be passed on to the next contributor who asked to be assigned to it.

_Note: This issue is for JWoC 2024 participants. If you are not participating in this event, please refrain from asking to get assigned to this issue._

**Comment by akarshi19** [comment]
please assign me this issue

**Comment by Sriparno08** [comment]
Hey @akarshi19, please mention the 'JWOC' (Case-Sensitive) keyword in your comment to be considered for assignment.

**Comment by suhani-sharma-ss** [comment]
I would like to work on this issue under JWOC

**Comment by Divyanshgarg-04** [comment]
@akarshi19 I would love to work on this issue under JWOC'24. Please assign this issue to me

**Comment by Prithwi32** [comment]
@Sriparno08 I would like to contribute to this issue under JWOC

**Comment by Sriparno08** [comment]
Hey @Prithwi32, another mentee @suhani-sharma-ss is already assigned to this issue.
