### ISSUE TITLE
UI: Change Padding of Program Container in 'Open Source Programs' Page

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#156]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

## Description

We need to change the padding of the highlighted section (in green) in the 'Open Source Programs' page from `20px` to `0 3rem`:

![image](https://github.com/Sriparno08/Openpedia/assets/89148144/f9030163-65d7-45c2-ae2c-c45d29aecc54)

**For Assignee:**

> Ensure that you submit a PR for this issue within 1 day. Otherwise, you will be unassigned from this issue and it will be passed on to the next contributor who asked to be assigned to it.

_Note: This issue is for JWoC 2024 participants. If you are not participating in this event, please refrain from asking to get assigned to this issue._

**Comment by jatinsinghkatal** [comment]
Hello, I would like to work on this issue under JWOC.
