### ISSUE TITLE
Feat: Create a 'Learn Git & GitHub' Page

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#157]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [ ] User Interface
- [x] Feature Request

## Description

We need to create a 'Learn Git & GitHub' page:

- Keep the theme intact
- Add some placeholder entries to the page as resources as the real ones will be dynamically inserted later
- The way in which each resource will show up is up to you

**For Assignee:**

> Ensure that you submit a PR for this issue within 4 days. Otherwise, you will be unassigned from this issue and it will be passed on to the next contributor who asked to be assigned to it.

_Note: This issue is for JWoC 2024 participants. If you are not participating in this event, please refrain from asking to get assigned to this issue._

**Comment by prasukjain07** [comment]
Hello mentor please assign this issue to me under JWC

**Comment by Sriparno08** [comment]
Hey @prasukjain07, you're assigned.

**Comment by thesri** [comment]
hey @Sriparno08 i would like to work on this under jwoc
