### ISSUE TITLE
Feat: Create a 'Beginner-Friendly Repos' Page

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#158]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [ ] User Interface
- [x] Feature Request

## Description

We need to create a 'Beginner-Friendly Repos' page:

- Keep the theme intact
- Add some placeholder entries to the page as resources as the real ones will be dynamically inserted later
- The way in which each resource will show up is up to you

**For Assignee:**

> Ensure that you submit a PR for this issue within 4 days. Otherwise, you will be unassigned from this issue and it will be passed on to the next contributor who asked to be assigned to it.

_Note: This issue is for JWoC 2024 participants. If you are not participating in this event, please refrain from asking to get assigned to this issue._

**Comment by ritu713** [comment]
Hey! Can you assign me this issue?

**Comment by akarshi19** [comment]
Please assign this issue under JWOC'24

**Comment by swetasingh8844** [comment]
@Sriparno08 please assign this issue to me under JWOC'24

**Comment by Sriparno08** [comment]
Hey @akarshi19, you're assigned.

To Others:

The mentee who is assigned to this issue is chosen because he/she was the first one to ask for assignment on or after 15th Jan, 2024 with the 'JWOC' keyword in his/her comment.
