### ISSUE TITLE
BUG: Inconsistent Font in "Openpedia" Text on FAQ Page

### ISSUE THREAD

**Issue by AftabMankapure** [Sriparno08/Openpedia#159]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

## Description

The font used for the "Openpedia" text on the FAQ page appears to be different from the font used on the home page. This inconsistency affects the visual coherence of the website and needs attention.

**Steps to Reproduce:**
1. Navigate to the "Home" page.
2. Observe the font used for the "Openpedia" text in the header.
3. Navigate to the "FAQ" page.
4. Note the font used for the "Openpedia" text in the FAQ page header.

**Expected Behavior:**
The font for the "Openpedia" text in the FAQ page header should match the font used on the home page, ensuring a consistent and professional appearance.

**Screenshots:**
Home page
![image](https://github.com/Sriparno08/Openpedia/assets/125949765/40af8566-0495-478b-aa52-49639be3d2a5)

FAQ page
![image](https://github.com/Sriparno08/Openpedia/assets/125949765/c47a3cba-1504-40cb-8a9b-7cfc8c8ebc85)

**System Configuration:**
- Laptop: HP Pavilion
- OS: Windows 11
- Browser: Chrome
- Version: 120.0.6099.201
Name: MDN Web Docs
Link: https://github.com/mdn/content
-->

**Comment by Sriparno08** [comment]
Hey @AftabMankapure, this issue has already been raised. So, we're closing this one.
