### ISSUE TITLE
Design can be improved | Features not working

### ISSUE THREAD

**Issue by tushargupta1504** [Sriparno08/Openpedia#162]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [ ] User Interface
- [ ] Feature Request

## Description

![image](https://github.com/Sriparno08/Openpedia/assets/138330699/c8b23b4e-38bd-49f5-8b73-eddf5a67f464)

**Comment by Jenis07** [comment]
hello sir, can you assign it to me under JWOC

**Comment by Sriparno08** [comment]
Hey @Jenis07, there's nothing to address in this issue. So, we're closing this one.
