### ISSUE TITLE
FEAT: Add feedback form

### ISSUE THREAD

**Issue by Sneha6003** [Sriparno08/Openpedia#165]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [ ] User Interface
- [X] Feature Request

## Description

I would like to work on this issue under JWOC.

**Comment by Sriparno08** [comment]
Hey @Sneha6003, it's a good idea. But we tend to use GitHub Discussions for receiving all kinds of feedback. So currently, we don't want to implement this idea and hence, we're closing this one.
