### ISSUE TITLE
UI: Change Footer Section Appearance

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#169]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

## Description

We need to change the footer section appearance by removing the `border-top-left-radius` property and turning the top portion to a straight line:

![image](https://github.com/Sriparno08/Openpedia/assets/89148144/3aa8cdcb-b928-4e52-a122-45c23172ba82)

**For Assignee:**

> Ensure that you submit a PR for this issue within 1 day. Otherwise, you will be unassigned from this issue and it will be passed on to the next contributor who asked to be assigned to it.

_Note: This issue is for JWoC 2024 participants. If you are not participating in this event, please refrain from asking to get assigned to this issue._

**Comment by this-is-yaash** [comment]
Assign me to this issue under JWOC

**Comment by this-is-yaash** [comment]
Is Bootstrap allowed to use?

**Comment by Sriparno08** [comment]
No, we don't want to add it for now.

**Comment by this-is-yaash** [comment]
Raised a PR, please review it.
