### ISSUE TITLE
UI: Add Display Property in Footer Section

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#170]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

## Description

We need to add the `display` property with a value of `block` to the link with the text 'Openpedia':

<p align="center">
  <img src="https://github.com/Sriparno08/Openpedia/assets/89148144/8d3b3a19-fba2-45ed-9b0c-c249d5d051c8">
</p>

**For Assignee:**

> Ensure that you submit a PR for this issue within 1 day. Otherwise, you will be unassigned from this issue and it will be passed on to the next contributor who asked to be assigned to it.

_Note: This issue is for JWoC 2024 participants. If you are not participating in this event, please refrain from asking to get assigned to this issue._

**Comment by TanushreeBorase** [comment]
Please assign me this under JWOC'24.

**Comment by Jenis07** [comment]
Can you assign it to me under JWOC

**Comment by Sriparno08** [comment]
@Jenis07 You're assigned.

@TanushreeBorase You are already assigned to another issue. Once you raise a PR for that issue and it's merged, you will be considered for assignment on other issues.

**Comment by Jenis07** [comment]
![image](https://github.com/Sriparno08/Openpedia/assets/100338684/d13790e0-12c2-4dc0-9cc5-be6ee606d18b)
sir is this right? for above mentioned issue..

**Comment by Sriparno08** [comment]
Yes, that's right.

**Comment by Jenis07** [comment]
so can i send the PR now?

**Comment by Sriparno08** [comment]
Yeah, sure.

**Comment by Jenis07** [comment]
is there any issue in the PR?\

**Comment by Sriparno08** [comment]
No, @Jenis07 and so, it's merged.
