### ISSUE TITLE
UI: Add Margin to Headings in Footer Section

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#171]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

## Description

We need to add margin to headings in footer section containing the text 'Support' and 'Categories':

<p align="center">
  <img src="https://github.com/Sriparno08/Openpedia/assets/89148144/82c726bd-75f8-4d49-ba12-0bd3e22bb278">
</p>

**For Assignee:**

> Ensure that you submit a PR for this issue within 1 day. Otherwise, you will be unassigned from this issue and it will be passed on to the next contributor who asked to be assigned to it.

_Note: This issue is for JWoC 2024 participants. If you are not participating in this event, please refrain from asking to get assigned to this issue._

**Comment by AryanPahuja21** [comment]
@Sriparno08 please assign this issue to me under JWOC'24

**Comment by TanushreeBorase** [comment]
Please assign me this issue under JWOC'24. In this issue we are supposed the increase the margin around the elements: Support and Category?

**Comment by Sriparno08** [comment]
@TanushreeBorase You're assigned.
