### ISSUE TITLE
UI: Format Data in Landing Page Footer

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#172]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

## Description

We need to format the data in the footer section of the landing page:

<p align="center">
  <img src="https://github.com/Sriparno08/Openpedia/assets/89148144/1857260f-1eb7-4c00-aa4b-921621bd4546">
</p>

Steps:

1. Break the span with the class `creator` into two spans
2. One span will have the class `copyright` and contain the text '© 2024 Openpedia'
3. The other span will have the class `creator` and contain the text 'Developed By Sriparno Roy & Open Source Community'
4. Keep the other existing one with the class `social media`
5. Distribute the spans using flexbox and `justify-content: space between`

**For Assignee:**

> Ensure that you submit a PR for this issue within 3 days. Otherwise, you will be unassigned from this issue and it will be passed on to the next contributor who asked to be assigned to it.

_Note: This issue is for JWoC 2024 participants. If you are not participating in this event, please refrain from asking to get assigned to this issue._

**Comment by AryanPahuja21** [comment]
@Sriparno08 pls assign me this issue under JWOC'24

**Comment by Sriparno08** [comment]
Hey @AryanPahuja21, you're assigned.
