### ISSUE TITLE
UI: Remove 'Discord' Icon From Landing Page Footer

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#173]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

## Description

We need to remove the 'Discord' icon from the footer section of the landing page:

<p align="center">
  <img src="https://github.com/Sriparno08/Openpedia/assets/89148144/1857260f-1eb7-4c00-aa4b-921621bd4546">
</p>

**For Assignee:**

> Ensure that you submit a PR for this issue within 1 day. Otherwise, you will be unassigned from this issue and it will be passed on to the next contributor who asked to be assigned to it.

_Note: This issue is for JWoC 2024 participants. If you are not participating in this event, please refrain from asking to get assigned to this issue._

**Comment by AryanPahuja21** [comment]
@Sriparno08 please assign this issue to me under JWOC'24

**Comment by TanushreeBorase** [comment]
Please assign me this issue @Sriparno08 under JWOC'24. I will try best to complete on time.

**Comment by Sriparno08** [comment]
@TanushreeBorase You're assigned.
