### ISSUE TITLE
UI: Remove 'Instagram' Icon From Landing Page Footer

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#174]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

## Description

We need to remove the 'Instagram' icon from the footer section of the landing page:

<p align="center">
  <img src="https://github.com/Sriparno08/Openpedia/assets/89148144/1857260f-1eb7-4c00-aa4b-921621bd4546">
</p>

**For Assignee:**

> Ensure that you submit a PR for this issue within 1 day. Otherwise, you will be unassigned from this issue and it will be passed on to the next contributor who asked to be assigned to it.

_Note: This issue is for JWoC 2024 participants. If you are not participating in this event, please refrain from asking to get assigned to this issue._

**Comment by AryanPahuja21** [comment]
@Sriparno08 please assign this issue to me under JWOC'24

**Comment by Vinaysohaliya** [comment]
@Sriparno08 Assign me to this issue under JWOC

**Comment by Sriparno08** [comment]
@Vinaysohaliya You're assigned.

**Comment by surendar-05** [comment]
@Sriparno08 Assign me to this issue under JWOC

**Comment by Sriparno08** [comment]
Hey @surendar-05, another mentee @Vinaysohaliya is already assigned to this issue.

**Comment by thatguywhocode** [comment]
Hey @Sriparno08 , can you assign me this issue under JWOC.

**Comment by Prithwi32** [comment]
@Sriparno08 I like to work on that issue under JWOC

**Comment by Sriparno08** [comment]
Hey @Vinaysohaliya, please submit a PR for this issue as soon as possible. If not, you will be unassigned from this issue.

**Comment by thatguywhocode** [comment]
hey @Sriparno08 , i would like to work on this issue under JWOC.

**Comment by Ananyamishra08** [comment]
hello @Sriparno08 , i would love to work on this under JWOC

**Comment by Sriparno08** [comment]
@surendar-05 You're assigned.

To Others:

The mentee who is assigned to this issue is chosen because he/she was the first one to ask for assignment with the 'JWOC' keyword in his/her comment.

**Comment by Syed0206** [comment]
@Sriparno08 Assign me to this issue under JWOC

**Comment by surendar-05** [comment]
I am ready with my pr under Jwoc
