### ISSUE TITLE
UI: Remove 'YouTube' Icon From Landing Page Footer

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#175]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

## Description

We need to remove the 'YouTube' icon from the footer section of the landing page:

<p align="center">
  <img src="https://github.com/Sriparno08/Openpedia/assets/89148144/1857260f-1eb7-4c00-aa4b-921621bd4546">
</p>

**For Assignee:**

> Ensure that you submit a PR for this issue within 1 day. Otherwise, you will be unassigned from this issue and it will be passed on to the next contributor who asked to be assigned to it.

_Note: This issue is for JWoC 2024 participants. If you are not participating in this event, please refrain from asking to get assigned to this issue._

**Comment by AryanPahuja21** [comment]
@Sriparno08 please assign this issue to me under JWOC'24

**Comment by Asin-Junior-Honore** [comment]
@Sriparno08  i would love to fix this

**Comment by Sriparno08** [comment]
Hey @Asin-Junior-Honore, this issue is for JWoC 2024 participants. Since you are not participating in this event, you can't be assigned to this issue.

**Comment by Asin-Junior-Honore** [comment]
@Sriparno08  alright understood

**Comment by this-is-yaash** [comment]
Assign me to this issue under **JWoC**

**Comment by Sriparno08** [comment]
Hey @this-is-yaash, please change 'JWoC' to 'JWOC' to be considered for assignment.

**Comment by this-is-yaash** [comment]
Yeah, 
Assign me to this issue under JWOC

**Comment by Sriparno08** [comment]
Hey @this-is-yaash, you're assigned.
