### ISSUE TITLE
[FEA]: The "More" option in category section should redirect to there respective youtube videos.

### ISSUE THREAD

**Issue by Ashutosh104** [Sriparno08/Openpedia#179]
## Category

- [x] Resource Addition
- [x] User Interface
- [x] Feature Request

## Description
In the category section, the "More" button in the boxes should redirect the user to their respective youtube videos.
![Screenshot 2024-01-18 184701](https://github.com/Sriparno08/Openpedia/assets/143163927/ae0e1f3e-95b0-44f3-b504-1f16f68e8bb8)

**Comment by Sriparno08** [comment]
Hey @Ashutosh104, these links should actually link to their respective pages in the domain. But the pages are not made yet, so the links will not work for now and hence, we're closing this one.
