### ISSUE TITLE
UI: Edit a button effect

### ISSUE THREAD

**Issue by madhurima316** [Sriparno08/Openpedia#183]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

## Description
Hover effect would be added to github button under 'About' section.

**Comment by madhurima316** [comment]
Please assign me this issue under JWOC 2024.

**Comment by Sriparno08** [comment]
Hey @madhurima316, there is a box shadow that is used as a hover effect to the 'GitHub' button and we want to keep it for now. So, we're closing this one.
