### ISSUE TITLE
Redesign Hero section

### ISSUE THREAD

**Issue by Shu12388y** [Sriparno08/Openpedia#185]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [ ] User Interface
- [ ] Feature Request

## Description
Redesign the hero section of the website 

![Screenshot (126)](https://github.com/Sriparno08/Openpedia/assets/91714143/b812657d-97b1-4917-9bc0-5239669ab383)

**Comment by Shu12388y** [comment]
@Sriparno08 can you assign this issue to under jwoc

**Comment by Sriparno08** [comment]
Please share a design with us so we can evaluate if it fits our project.

Also, please change 'jwoc' to 'JWOC' to be considered for assignment.

**Comment by Shu12388y** [comment]
@Sriparno08 I have redesign the hero section 

![image](https://github.com/Sriparno08/Openpedia/assets/91714143/44b9ca2a-3bb4-423b-b296-47bbb101da53)

**Comment by Sriparno08** [comment]
Looks good, @Shu12388y. Among these changes, we only want to implement the image as we want to keep the theme intact.

To be considered for assignment, please change 'jwoc' to 'JWOC' in your comment.

**Comment by Lakshya0018UP** [comment]
Can you assign it to me under JWOC

**Comment by Sriparno08** [comment]
Hey @Lakshya0018UP, you're assigned.

@Shu12388y The mentee who is assigned to this issue is chosen because he/she was the first one to ask for assignment with the 'JWOC' (Case-Sensitive) keyword in his/her comment.

**Comment by Sriparno08** [comment]
Hey @Lakshya0018UP, you're assigned.

@Shu12388y The mentee who is assigned to this issue is chosen because he/she was the first one to ask for assignment with the 'JWOC' (Case-Sensitive) keyword in his/her comment.

**Comment by Lakshya0018UP** [comment]
So who would be doing it me or @Shu12388y ?

**Comment by Lakshya0018UP** [comment]
Do you just want the image?

**Comment by Sriparno08** [comment]
@Lakshya0018UP Yes, only the image.

**Comment by Lakshya0018UP** [comment]
![image](https://github.com/Sriparno08/Openpedia/assets/122142987/53a82670-9700-4918-9111-f9bdc7ba584b)

Is this correct @Sriparno08 , or any other changes as you said theme has to be intact

**Comment by Sriparno08** [comment]
@Lakshya0018UP You did it vertically. Please do it horizontally like the one suggested at the start of the issue.

**Comment by Lakshya0018UP** [comment]
![image](https://github.com/Sriparno08/Openpedia/assets/122142987/2bfd348b-65de-47d0-bf7d-903edfc09efd)


@Sriparno08 See this now

**Comment by Sriparno08** [comment]
@Lakshya0018UP Yeah, this looks good 👍
