### ISSUE TITLE
Feat: Create and Add Logo to Title bar and Navbar

### ISSUE THREAD

**Issue by antilneeraj** [Sriparno08/Openpedia#190]
## Category

- [x] Resource Addition
- [x] User Interface
- [x] Feature Request

## Description

Add a Logo (.svg format) for Openpedia that matches the theme.

## Screenshot

![logo](https://github.com/Sriparno08/Openpedia/assets/98269887/0af1b82c-43ce-48ad-b363-9c6a824e5e43)
![logo1](https://github.com/Sriparno08/Openpedia/assets/98269887/41df9408-7fd9-4f8b-a8f0-95aef03e7795)

Can you please assign this issue to me under JWOC. and Please set the necessary labels.

**Comment by antilneeraj** [comment]
@Sriparno08 I have made it in `SVG` you can also give some color suggestions according to you to match the theme of the website

**Comment by Sriparno08** [comment]
The logos look good, @antilneeraj. Can you change the font of the longer one to match it with the one that we're currently using (if not using already)?

**Comment by antilneeraj** [comment]
@Sriparno08 Just to inform you the whole logo is made from path element and not any text element so changing the font family would not be that easy...

By the way I can replace the paths with text elements. But initially it looks good. 

I don't think there would be any problem with the font. Generally, logos have a different font-family than the rest website.

But if you still feel any need to change the font, I'll be okay with that just tell me the name of the `font-family` you wish to be in the logo.

**Comment by Sriparno08** [comment]
Got it, @antilneeraj. In this case, we can keep the current one as it looks good enough. Let's see how it looks on the website.

I'm assigning this to you.
