### ISSUE TITLE
[Feat] : Adding the same footer to "Beginner-Friendly Repos" page

### ISSUE THREAD

**Issue by Ananyamishra08** [Sriparno08/Openpedia#199]
## feature

Adding the same footer seen on main page to "Beginner-Friendly Repos" page.
![1](https://github.com/Sriparno08/Openpedia/assets/98649189/eaf8186e-15bd-446e-b93f-2c28f38b4dde)

**Comment by Ananyamishra08** [comment]
hey @Sriparno08 assign me this issue under JWOC

**Comment by Ananyamishra08** [comment]
Assign me this under the label easy or medium

**Comment by Sriparno08** [comment]
@Ananyamishra08 You're assigned.
