### ISSUE TITLE
Replace Toggle button with appropriate dark mode button.

### ISSUE THREAD

**Issue by vishapraj** [Sriparno08/Openpedia#201]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [ ] User Interface
- [ ] Feature Request

**Comment by vishapraj** [comment]
Pls Assign me this issue.

**Comment by Sriparno08** [comment]
Hey @vishapraj, nice idea.

Please mention the 'JWOC' (Case-Sensitive) keyword in your comment to get considered for assignment.

**Comment by vishapraj** [comment]
pls assign me under 'JWOC'

**Comment by Sriparno08** [comment]
@vishapraj You're assigned.

**Comment by Syed0206** [comment]
@Sriparno08 Please assign me this issue under JWOC
