### ISSUE TITLE
Replacement of the Dark mode button

### ISSUE THREAD

**Issue by prakharsingh-74** [Sriparno08/Openpedia#203]
Issue Description:
The current implementation of the dark mode button in our application is not good UI and the first user that comes on the website cannot be able to detect that so the replacement is necessary. This documentation outlines the problem, proposed solution, and any additional considerations related to this issue.

Problem:
The existing dark mode button has been reported to have the following issues:

Not good UI design.
Visual glitches and rendering problems.
User feedback indicating difficulty in toggling dark mode.
Proposed Solution:
To address the issues mentioned above, we propose the replacement of the current dark mode button with a more robust and user-friendly implementation. The new dark mode button should adhere to the following guidelines:

Consistency: Ensure consistent behavior across various devices and browsers.
Visual Appeal: Design a visually appealing dark mode button that integrates seamlessly with the overall user interface.
Accessibility: Ensure that the dark mode toggle is accessible and easy to use for all users, including those with disabilities.
User Feedback: Implement clear feedback mechanisms, such as visual indicators and tooltips, to inform users about the state of dark mode.
Implementation Plan:
Design:

Work with the design team to create a visually appealing dark mode button that aligns with the application's design language.
Consider user feedback on the existing button and incorporate improvements in the new design.
Development:

Replace the current dark mode button with the newly designed one.

Uploading 
![Screenshot 2024-01-21 044510](https://github.com/Sriparno08/Openpedia/assets/148339919/36ff386a-6449-4a0b-b1e0-8132cb9ccdfe)

SO PLEASE ASSIGN ME THIS ISSUE UNDER JWOC 24

**Comment by prakharsingh-74** [comment]
Please Assign me this issue under JWOC 24

**Comment by Sriparno08** [comment]
Hey @prakharsingh-74, good idea. However, we already have an issue on the same topic. So, we're closing this one.
