### ISSUE TITLE
FEAT: Improve Dark Mode Toggling Button and Consistency

### ISSUE THREAD

**Issue by ramith-kulal** [Sriparno08/Openpedia#205]
## Category

- [X] Documentation
- [X] Resource Addition
- [X] Codebase
- [X] User Interface
- [X] Feature Request

## Description
The current dark mode **toggling button** on the website lacks visual appeal and the dark mode seems **inconsistent** in some parts like **go to top button**, And would also like to add an customized **scroll bar** to the website which would work accord to the theme. The Goto top button gets **overlapped with the insta,git,linkedin logos** present in the footer which needs to be fixed.

 **Current Look:**
![Screenshot 2024-01-21 100703](https://github.com/Sriparno08/Openpedia/assets/142984776/ca5dd176-a0c0-44f4-9c30-d8f8b733eef4)
**Go-to-top button getting overlapped:**
![Screenshot 2024-01-21 101258](https://github.com/Sriparno08/Openpedia/assets/142984776/bbb03ffe-2ec8-4130-b6ae-f6e0ceb8f227)

**Working under JWoC'24**

**Comment by Sriparno08** [comment]
Hey @ramith-kulal, we already have an issue on the same topic. So, we're closing this one.
