### ISSUE TITLE
Issue:  "Go to Top" Button Overlapping Footer Logos

### ISSUE THREAD

**Issue by ramith-kulal** [Sriparno08/Openpedia#206]
## Category

- [X] Documentation
- [X] Resource Addition
- [X] Codebase
- [X] User Interface
- [X] Feature Request

## Description
The  "Go to Top" button is currently overlapping with the footer logos, including GitHub, LinkedIn, and others.

**Expected Behavior:**
- The  "Go to Top" button should not overlap with any other elements on the page.
- Ensure that the footer logos, including GitHub, LinkedIn, and insta, are properly displayed without any overlap.
**Screenshots:**
![Screenshot 2024-01-21 101258](https://github.com/Sriparno08/Openpedia/assets/142984776/05a1d0f1-44c4-4ce2-9d5c-2fb11c65c75a)

**Working under JWOC**

**Comment by Sriparno08** [comment]
Hey @ramith-kulal, good suggestion. Please change 'JWoC' to 'JWOC' since this keyword needs to be case-sensitive.

**Comment by ramith-kulal** [comment]
> Hey @ramith-kulal, good suggestion. Please change 'JWoC' to 'JWOC' since this keyword needs to be case-sensitive.

Done

**Comment by Sriparno08** [comment]
@ramith-kulal You're assigned.
