### ISSUE TITLE
<FEAT>: Add a resources page

### ISSUE THREAD

**Issue by rishicds** [Sriparno08/Openpedia#211]
## Category

- [ ] Documentation
- [X] Resource Addition
- [X] Codebase
- [ ] User Interface
- [X] Feature Request

## Description

Hi, I'd like to add a page where the user can learn what tech stacks to use and where to learn them in order to contribute to Open Source efficienty

I want to add roadmaps from developer roadmaps and all the necessary links.

Please assign this issue to me under JWOC'24

**Comment by Sriparno08** [comment]
Hey @rishicds, we currently want to stick to 5 pages where each page will list resources for each category. So, we're closing this issue.
