### ISSUE TITLE
Add links on categories  menu options (Introductiont to OpenSource , Learn Git& Github .......)

### ISSUE THREAD

**Issue by vishapraj** [Sriparno08/Openpedia#212]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [ ] User Interface
- [ ] Feature Request

**Comment by vishapraj** [comment]
Pls label this issue's difficulty level and assign me under 'JWOC'

**Comment by Sriparno08** [comment]
@vishapraj You're assigned.

**Comment by vishapraj** [comment]
![Screenshot from 2024-01-21 22-30-06](https://github.com/Sriparno08/Openpedia/assets/126682925/aca3230b-94d1-4cc0-b4dc-85b216fb8408)
getting error , how to fix?

**Comment by Sriparno08** [comment]
@vishapraj The `--set-upstream` command is no longer supported. Plus, there is a problem with password authentication.

So, you are suggested to start a fresh process. It seems like you want to link the local branch 'openpedia' with the remote branch 'openpedia' and then push your changes from local to remote. If that's the case, here are the steps:

1. Update the remote branch 'openpedia'
2. Use the `git switch openpedia' command locally to fetch the remote branch to the local machine and switch to it. In this case, the local and remote branches will be automatically linked to each other.
3. Make your changes and commit
4. Push your changes using `git push origin openpedia` and make a PR

**Comment by vishapraj** [comment]
@Sriparno08 pls review my PR
