### ISSUE TITLE
Bug: Text not visible in dark mode on the home page

### ISSUE THREAD

**Issue by gitgoap** [Sriparno08/Openpedia#216]
## BUG

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [X] User Interface
- [ ] Feature Request

## Description
Some text given on the homepage is not visible in the **darkmode**. Refer screenshots

### Light mode: 
![Screenshot 2024-01-22 071722](https://github.com/Sriparno08/Openpedia/assets/117789470/64fd2a49-aa79-4fa1-a3b5-06997ab4f4d1)

### Dark mode:
![Screenshot 2024-01-22 071733](https://github.com/Sriparno08/Openpedia/assets/117789470/713504c6-c963-4f62-9dd5-0bcfb7846e82)

**Comment by gitgoap** [comment]
Can I work on this issue? 
Thanks!

**Comment by Sriparno08** [comment]
Hey @gitgoap, good idea. Rather than working on the text, you can change the background to match with the other sections in dark mode. This will make the text automatically visible.

Also, please mention the 'JWOC' (Case-Sensitive) keyword in your comment to be considered for assignment.

**Comment by gitgoap** [comment]
@Sriparno08 Okay! Assign this issue to me under JWOC 2024! 
I'll work on it!
