### ISSUE TITLE
UI: Change Font Size of Copyright Text

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#219]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

## Description

We need to change the font size of the landing page copyright text from `13px` to `16px`:

<p align="center">
  <img src="https://github.com/Sriparno08/Openpedia/assets/89148144/7db61e87-b399-49c6-885b-dd469b2f9c87">
</p>

**For Assignee:**

> Ensure that you submit a PR for this issue within 1 day. Otherwise, you will be unassigned from this issue and it will be passed on to the next contributor who asked to be assigned to it.

_Note: This issue is for JWoC 2024 participants. If you are not participating in this event, please refrain from asking to get assigned to this issue._

**Comment by Hemant5104** [comment]
I would  like to work on this issue under jwoc24

**Comment by vishal2005025** [comment]
I have read the issue and I would like to work on this issue.
Please assign it to me under JWOC'2024.

**Comment by Sriparno08** [comment]
@vishal2005025 You're assigned.

To Others:

The mentee who is assigned to this issue is chosen because he/she was the first one to ask for assignment with the 'JWOC' (Case-Sensitive) keyword in his/her comment.

**Comment by Sriparno08** [comment]
@SharmaDhruv2511 You're right. But the mentee needs to include 'JWOC' (Case-Sensitive) in his/her comment. In this case, you entered 'jwoc' which is not case-sensitive.

Plus, you're currently assigned to another issue. So, you can work on that.
