### ISSUE TITLE
UI: Change Font Size of Creator Text

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#220]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

## Description

We need to change the font size of the landing page creator text from `10px` to `16px`:

<p align="center">
  <img src="https://github.com/Sriparno08/Openpedia/assets/89148144/42010b6d-e776-4d23-978f-bfadf9a18805">
</p>

**For Assignee:**

> Ensure that you submit a PR for this issue within 1 day. Otherwise, you will be unassigned from this issue and it will be passed on to the next contributor who asked to be assigned to it.

_Note: This issue is for JWoC 2024 participants. If you are not participating in this event, please refrain from asking to get assigned to this issue._

**Comment by AryanPahuja21** [comment]
@Sriparno08 please assign this issue to me under JWOC'24

**Comment by Jenis07** [comment]
Can you please assign me this issue under JWOC?

**Comment by vishal2005025** [comment]
I have read the issue and I would like to work on this issue.
Please assign it to me under JWOC'2024.
