### ISSUE TITLE
UI: Add Margin to Social Links

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#222]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

## Description

We need to add a `margin-right` of  `1rem` to the social links in the landing page footer. Make sure that you don't add that to the last link:

<p align="center">
  <img src="https://github.com/Sriparno08/Openpedia/assets/89148144/a8f66b01-b13e-484e-8a52-f2e521ba70f7">
</p>

**For Assignee:**

> Ensure that you submit a PR for this issue within 1 day. Otherwise, you will be unassigned from this issue and it will be passed on to the next contributor who asked to be assigned to it.

_Note: This issue is for JWoC 2024 participants. If you are not participating in this event, please refrain from asking to get assigned to this issue._

**Comment by antilneeraj** [comment]
Hey @Sriparno08, I would like to work on this issue under JWOC.

**Comment by Sriparno08** [comment]
@antilneeraj You're assigned.
