### ISSUE TITLE
UI: Change Font Size of Footer Headers

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#224]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

## Description

We need to change the font size of the landing page footer headers ('Support' &' Categories') to `15px`:

<p align="center">
  <img src="https://github.com/Sriparno08/Openpedia/assets/89148144/05900e88-c08f-497e-9c58-68a3d439d468">
</p>

**For Assignee:**

> Ensure that you submit a PR for this issue within 1 day. Otherwise, you will be unassigned from this issue and it will be passed on to the next contributor who asked to be assigned to it.

_Note: This issue is for JWoC 2024 participants. If you are not participating in this event, please refrain from asking to get assigned to this issue._

**Comment by SharmaDhruv2511** [comment]
I want to work on it. Can you please assign it to me? @Sriparno08

**Comment by Jenis07** [comment]
Can you please assign me this issue under JWOC?

**Comment by vishal2005025** [comment]
I have read the issue and I would like to work on this issue.
Please assign it to me under JWOC'2024.

**Comment by SharmaDhruv2511** [comment]
If i add the style option  in their respective tag and add the font size in it , is it okay ?? @Sriparno08

**Comment by SharmaDhruv2511** [comment]
![image](https://github.com/Sriparno08/Openpedia/assets/102755411/2b3e929d-c8e3-4416-aabd-694ca885ef27)

![image](https://github.com/Sriparno08/Openpedia/assets/102755411/b6841dc4-f10f-434b-b714-3a6c06b0d2e7)


looks good @Sriparno08

**Comment by Sriparno08** [comment]
Yeah, it's okay.

**Comment by SharmaDhruv2511** [comment]
please review the PR @Sriparno08
