### ISSUE TITLE
<Feature Request>: <Addition of Contributor's Section>

### ISSUE THREAD

**Issue by GhoshAditi** [Sriparno08/Openpedia#240]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [ ] User Interface
- [X] Feature Request

## Description
I would like to add the contributor's section . plz assign this to me under JWOC'24.

**Comment by GhoshAditi** [comment]
@Sriparno08 i would like to work on it. plz assign it to me under jwoc'24.

**Comment by GhoshAditi** [comment]
@antilneeraj plz check

**Comment by vermaanurag1532** [comment]
please Assign it to me

**Comment by Sriparno08** [comment]
Hey @GhoshAditi, if you want to add it to README.md, then it is currently not possible as documentation improvements are not considered as valid contributions.

If you want to add it to the website, then the thing is that we want to rather have a 'Contributors' link at the landing page footer that links to Openpedia (Repo) -> Insights -> Contributors. So, we're closing this one.
