### ISSUE TITLE
slight changing 

### ISSUE THREAD

**Issue by Gokilp** [Sriparno08/Openpedia#242]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

**Comment by Sriparno08** [comment]
Please explain the changes that you want to address in this issue.

Also, please mention the 'JWOC' (Case-Sensitive) keyword in your comment to be considered for assignment.

**Comment by Gokilp** [comment]
I can fix the issues by adding a  box radius on Css file It feel looks on good Ui experience
