### ISSUE TITLE
Change `Button Style`

### ISSUE THREAD

**Issue by this-is-yaash** [Sriparno08/Openpedia#244]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

## Description
Actually the idea of adding this button style to this site's theme doesn't look good.
It looks weird & outdated with its gradient design (when switched on to dark, it basically turn light mode) & and implementation.

I propose to add a new button which matches the site theme.
![image](https://github.com/Sriparno08/Openpedia/assets/84762257/1602e31c-1590-4635-bc75-81abd50ea102)

If this issue is valid, then assign me to work on this issue under **JWOC**

**Comment by Sriparno08** [comment]
@this-is-yaash Good idea.

If you can, make it like the following one.

I'm assigning this to you.

https://github.com/Sriparno08/Openpedia/assets/89148144/b464c3b5-da9a-46c1-b689-1e5ead1b952a

**Comment by this-is-yaash** [comment]
Yeah sure👍

**Comment by Gokilp** [comment]
need a any help

**Comment by this-is-yaash** [comment]
@Sriparno08 Submitted PR #251
