### ISSUE TITLE
The design is looking not so great order can be improved hre

### ISSUE THREAD

**Issue by tushargupta1504** [Sriparno08/Openpedia#253]
I want improve the design as design aand algn. ca be improved . (JWOC)
![image](https://github.com/Sriparno08/Openpedia/assets/138330699/49e0d864-7eba-4e9c-8be3-a1c6aa44f747)

**Comment by Sriparno08** [comment]
@tushargupta1504 Sounds good!

Please mention the 'JWOC' keyword in your description to be considered for assignment.

**Comment by Sriparno08** [comment]
@tushargupta1504 Please submit a PR for this issue as soon as possible. Otherwise, you will be unassigned from this issue.

**Comment by tushargupta1504** [comment]
Yeah

**Comment by Sneha123-zudo** [comment]
I am interested in this issue, please assign me this issue

**Comment by antilneeraj** [comment]
@Sriparno08 As the time limit has exceeded and the assignee hasn't pushed any PR yet. So, I request you to please assign this issue to me under JWOC.
