### ISSUE TITLE
[Feature]: Enhance Contributor Onboarding -Add Local Installation Video to README

### ISSUE THREAD

**Issue by rahat2134** [Sriparno08/Openpedia#255]
## Category
- [X] Documentation
- [X] Resource Addition
- [X] Feature Request

## Description

Contributor onboarding could be improved by providing a visual guide on how to install the project locally. Adding a video demonstration will help newcomers understand the setup process more effectively.

Expected Outcome:
The addition of a video tutorial in the README, demonstrating the step-by-step process of installing the project locally, will make it easier for contributors, especially those new to the codebase.

Proposed Content:
A short video covering the following:

Cloning the repository.
Installing dependencies.
Configuring any necessary settings.
Running the project locally.
Problem
Contributor onboarding could be improved by providing a visual guide on how to install the project locally. Adding a video demonstration will help newcomers understand the setup process more effectively.

Proposed Solution
Record a concise video for that.
Link: https://github.com/mdn/content
-->

**Comment by rahat2134** [comment]
@Sriparno08 assign me this under JWOC.

**Comment by Sriparno08** [comment]
That's a good idea. But unfortunately, documentation improvements are not considered as valid contributions for JWOC. So, we will have to close this one.
