### ISSUE TITLE
Feature: Adding a webpage for opensource program with official website link in the form of CSS cards

### ISSUE THREAD

**Issue by gitgoap** [Sriparno08/Openpedia#257]
# Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [ ] User Interface
- [x] Feature Request

# Description

Proposing to add a webpage in the site that will have all the program picture , little about them and offical link in the form of CSS cards.
![Screenshot 2024-01-26 044727](https://github.com/Sriparno08/Openpedia/assets/117789470/315e00e2-2bd4-4059-ba9a-b42e21f22451)

Link of the this page would be present on the navbar.
![Screenshot 2024-01-26 045030](https://github.com/Sriparno08/Openpedia/assets/117789470/95e976d8-bba1-486b-8617-a1689a1d85c6)

**Comment by gitgoap** [comment]
Hi!
Can I work on this under JWOC 2024?
Thanks!

**Comment by Sriparno08** [comment]
@gitgoap We already have an 'Open Source Programs' page on the website. So, we're closing this one.

![image](https://github.com/Sriparno08/Openpedia/assets/89148144/97b1a866-1665-47e4-bbc0-e08663a0851c)
