### ISSUE TITLE
UI: Replace and align the Hero Section Image

### ISSUE THREAD

**Issue by antilneeraj** [Sriparno08/Openpedia#258]
## Category

- [x] Resource Addition
- [x] User Interface
- [x] Responsive 

## Description

The existing image is not matching the theme of the website and is also stretched a bit. I want to replace that image with a themed transparent image with proper aspect ration hence making it compatible with all screen sizes.

### Existing Image:
![image](https://github.com/Sriparno08/Openpedia/assets/98269887/baa41108-9061-41c7-beca-14a4fcea7941)

**Comment by antilneeraj** [comment]
@Sriparno08 Please assign this issue to me under JWOC.

**Comment by Sriparno08** [comment]
@antilneeraj Please share a preview so that we can understand the difference.

**Comment by antilneeraj** [comment]
## Preview

### Light Mode

![image](https://github.com/Sriparno08/Openpedia/assets/98269887/4b4b1032-adb6-4c0e-86ff-73b37b712254)
![image](https://github.com/Sriparno08/Openpedia/assets/98269887/5cd5d02a-1bf1-4852-9d91-cbbaf46e61d0)

### Dark Mode

![image](https://github.com/Sriparno08/Openpedia/assets/98269887/11ed24f4-a221-472c-9bb3-e64854d50bc4)
![image](https://github.com/Sriparno08/Openpedia/assets/98269887/42333eac-2d69-4123-97af-b3fe78c99bfe)

**Comment by Sriparno08** [comment]
Looks good. I'm assigning this to you.
