### ISSUE TITLE
UI: alignment of social media links and copyright

### ISSUE THREAD

**Issue by Hemant5104** [Sriparno08/Openpedia#259]
I would like to work on that issue under JWOC'24 

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

**Comment by Prithwi32** [comment]
@Sriparno08  I would like to work on this issue under JWOC

**Comment by Sriparno08** [comment]
@Hemant5104 The things are looking well-aligned in the landing page. Can you explain more about it?

**Comment by Hemant5104** [comment]
![Screenshot 2024-01-16 011535](https://github.com/Sriparno08/Openpedia/assets/143774541/5cf75317-4f97-4609-a62b-fe366398d86b)
Social Media links should be right above the **developed by sriparno roy section** or should be in support section and copyright mark should be in vertical alignment with  **developed by sriparno roy section**

**Comment by Sriparno08** [comment]
Just like the below image, we want to keep the social media links at the bottom and we want to keep the other two sections ('Copyright' & 'Developed By') at the same row. So, let's keep the formation.

In case of the vertical alignment of the 'Copyright' button, we can do that. So, I'm assigning this to you.

**Comment by Hemant5104** [comment]
![Screenshot 2024-01-28 155050](https://github.com/Sriparno08/Openpedia/assets/143774541/30e4d601-9ffd-4025-87ef-51f48c05c3c3)
Is this alright, or should i make any other changes??
