### ISSUE TITLE
Add contact us page.

### ISSUE THREAD

**Issue by Sneha123-zudo** [Sriparno08/Openpedia#260]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [x] Codebase
- [x] User Interface
- [x] Feature Request

## Description
Want to add a contact us page where the users can be in touch with us . Please assign me this issue under JWOC ' 24

**Comment by Sriparno08** [comment]
@Sneha123-zudo Good idea. But currently, we don't want to implement it to the website as we have the social links and GitHub Discussions to help with that. So, we're closing this one.
