### ISSUE TITLE
Fix : Minor problems in `Home page` & `FAQ page`

### ISSUE THREAD

**Issue by this-is-yaash** [Sriparno08/Openpedia#261]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [x] Feature Request

## Description
**FAQ Page has lot of unfinished stuffs, they are**:

- In Footer, under **Categories** section - link redirecting is  not working.
![image](https://github.com/Sriparno08/Openpedia/assets/84762257/11c8806f-50c1-413b-a91a-7f0e97434248)

- Adding Dark Mode to FAQ, which is currently missing in that page specifically.
- FAQ Page has been cropped, hiding the Headers slightly, need to align it properly.
- There is an Unnecessary Menu Icon Present in FAQ page near the Openpedia Icon.
![image](https://github.com/Sriparno08/Openpedia/assets/84762257/9f1a8f73-fbd0-43c9-afba-885cead35f3d)

**Home Page**:

When the dark mode is turned on, the **GitHub** button disappears shows only the text.
![image](https://github.com/Sriparno08/Openpedia/assets/84762257/7801759d-5ae1-411c-889d-eb40a883b1e1)

- need to add styles to the button to make it visible in dark mode. 

If the issue is valid, then assign me to work on this issue under **JWOC**

**Comment by Sriparno08** [comment]
@this-is-yaash Nice suggestions. I'm assigning this to you.

**Comment by this-is-yaash** [comment]
Submitted PR #270 
@Sriparno08 
Please review it
