### ISSUE TITLE
Feature: Add hover effect on social media icons

### ISSUE THREAD

**Issue by Anikett11** [Sriparno08/Openpedia#262]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

## Description

JWOC

**Comment by Sriparno08** [comment]
You're assigned.

**Comment by thesri** [comment]
@Sriparno08 please assign this to me under jwoc 2024

**Comment by Sriparno08** [comment]
@Anikett11 Please submit a PR for this issue as soon as possible. Otherwise, you will be unassigned from this issue.
