### ISSUE TITLE
Scroll back to top button is not present in all pages 

### ISSUE THREAD

**Issue by Sneha123-zudo** [Sriparno08/Openpedia#265]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

## Description
 I want to add scroll back to top button to all the pages , it is not present in all pages. Please assign me this issue under jwoc

**Comment by Sriparno08** [comment]
You're assigned.

**Comment by thesri** [comment]
@Sriparno08 please assign this to me under jwoc 2024 , if the assigned mentee couldnt do it in assignted time
