### ISSUE TITLE
Feature Request:  A feedback form about the documentation

### ISSUE THREAD

**Issue by thesri** [Sriparno08/Openpedia#268]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [ ] User Interface
- [x ] Feature Request

## Description
A feed back form about the documentation which will let us know how useful the information was and what to improve. please assign this issue under jwoc 2024

**Comment by Sriparno08** [comment]
For now, we want to use GitHub discussions for receiving all kinds of feedback. So, we will have to close this one.
