### ISSUE TITLE
#Feature : Add hover effect on buttons on home page 

### ISSUE THREAD

**Issue by vishal2005025** [Sriparno08/Openpedia#272]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

## Description
Add hover effect on buttons like more button , github button on home page ..

**Comment by leynarhuynh** [comment]
Hi! I'm new to open source contribution but would love to give this issue a shot.

**Comment by vishal2005025** [comment]
Sorry,  But I am also a beginner to open source contribution . I would like to work on this issue..

**Comment by Sriparno08** [comment]
@vishal2005025 Both the 'More' and the 'GitHub' button have a hover effect on them, which are looking fine. So, we don't want to change them for now and hence, we're closing this issue.
