### ISSUE TITLE
Enhance : `Image` in Home Page with visual effects 

### ISSUE THREAD

**Issue by this-is-yaash** [Sriparno08/Openpedia#273]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

## Description

Current image in Home page looks weird & doesn't match the UI. 
So I propose to change the image, also adding a logic to not change ratio of the image.

If it's valid, then assign this issue to me under **JWOC**

**Comment by this-is-yaash** [comment]
@Sriparno08 
This is from **GirlScript SoC**, now I'm thinking of doing something like this in home page's image.
- Hover : makes the image move
- Color changes for dark mode & light mode, and
- Image moving up & down effect

[Screencast from 2024-01-28 19-22-05.webm](https://github.com/Sriparno08/Openpedia/assets/84762257/a4577f74-b613-410a-8292-94bb28783102)

If you think that this is a good idea to implement, then assign this issue to me under **JWOC**.

Thanks!

**Comment by Sriparno08** [comment]
@this-is-yaash The image is recently changed and it's looking good. So, we don't want to change that. In case of animations, we don't want to implement it for now. So, we're closing this issue.
