### ISSUE TITLE
Feature : Add Contact Us Page to this website.

### ISSUE THREAD

**Issue by SohanRC** [Sriparno08/Openpedia#276]
## Category

- [X] User Interface
- [X] Feature Request

## Description
Add a contact us page in this Website .
I am providing the screenshot below !

![Responsive-Contact-Form](https://github.com/Sriparno08/Openpedia/assets/124901633/c192cfdf-e0c0-4efa-89d4-517e7563934b)

**Comment by SohanRC** [comment]
Please assign me under JWOC 2024.

**Comment by Sriparno08** [comment]
@SohanRC For now, we want to use the social links and GitHub discussions as the medium for contacting us rather than a 'Contact Us' page. So, we're closing this issue.
