### ISSUE TITLE
Feature  : Add a Carousel in the hero section rather than a still picture !.

### ISSUE THREAD

**Issue by SohanRC** [Sriparno08/Openpedia#278]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [ ] User Interface
- [X] Feature Request

## Description
Add a Carousel in the hero section rather than a still picture !.

**Comment by Sriparno08** [comment]
@SohanRC A carousel looks nice, but in the case of this website, we want to keep a single picture for now. So, we're closing this issue.
