### ISSUE TITLE
Favicon icon is not linked and the some pages are not linked with navbar

### ISSUE THREAD

**Issue by Sneha123-zudo** [Sriparno08/Openpedia#281]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

## Description
I want to add a favicon icon to pages where it is not present , like some pages present in categories does not have favicon icon .
And also some pages of navbar are not properly linked like, pages in categories section have navbar and they are not linked.
I want to fix both these issues please assign me this issue under JWOC'24.

**Comment by Sriparno08** [comment]
@Sneha123-zudo Sounds good. I'm assigning this to you.
