### ISSUE TITLE
BUG : Incorrect names of the categories pages on the title bar

### ISSUE THREAD

**Issue by Abidsyed25** [Sriparno08/Openpedia#283]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [X] User Interface
- [ ] Feature Request

## Description

Some of the categories pages title bar name is incorrect. I want to set a proper title in the title bar of all categories pages. I am attaching a screenshot below for reference. 

**Text in the title bar of "Learn Git & Github" category page is incorrect.**

JWOC

![title](https://github.com/Sriparno08/Openpedia/assets/116893970/c1b1f849-fa64-48c1-b91a-c2aeb76b9262)

**Comment by Sriparno08** [comment]
@Abidsyed25 Sounds good. I'm assigning this to you.
