### ISSUE TITLE
Designs of Beginner Friendly Repos and Open source program are not looking good

### ISSUE THREAD

**Issue by Sneha123-zudo** [Sriparno08/Openpedia#293]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

## Description
The Design of Beginner Friendly Repos and Open Source Programs are not looking good , i want to improve both these pages. 
Please assign me this issue under JWOC'24.

**Comment by Divyanshgarg-04** [comment]
@Sriparno08 I would love to work on this issue under JWOC. Please assign this issue to me

**Comment by Sriparno08** [comment]
@Sneha123-zudo You're assigned.

**Comment by harshvardhan614** [comment]
@Sriparno08 I have the experience to create beautiful UI designs, Can you assign this issue to me so I contribute to this project?

**Comment by Sriparno08** [comment]
@harshvardhan614 This issue is closed. So, it can't be assigned to you or anyone else.
