### ISSUE TITLE
BUG: Fix the Sticky Navbar for smaller screens

### ISSUE THREAD

**Issue by antilneeraj** [Sriparno08/Openpedia#298]
## Category

- [x] User Interface

## Description

The Navbar of the website is Sticky for the Desktop view. But for mobiles it is not
I want to fix this issue to enhance user experience while surfing the website and make it more convenient for mobile users to navigate to other pages or switch between themes easily

### Desktop View - Sticky
![image](https://github.com/Sriparno08/Openpedia/assets/98269887/b3ddd620-ece4-428b-b558-7d7195f09605)

### Mobile View - Needs to be Sticky
![image](https://github.com/Sriparno08/Openpedia/assets/98269887/26c6fe02-7817-4c87-af52-4885f60d89d5)

**Comment by antilneeraj** [comment]
@Sriparno08 Kindly assing this issue to me under JWOC.

**Comment by Sriparno08** [comment]
You're assigned.
