### ISSUE TITLE
Feature Request : Build Contact Us Section

### ISSUE THREAD

**Issue by PranavBarthwal** [Sriparno08/Openpedia#300]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [x] User Interface
- [ ] Codebase
- [x] Feature Request

## Description

I would like to make a contact us section for Openpedia, under JWoC'24.
Inspiration :
![Screenshot 2024-02-02 230016](https://github.com/Sriparno08/Openpedia/assets/110532770/437b02a6-986b-45b3-b399-43609bf0233d)

**Comment by Sriparno08** [comment]
@PranavBarthwal Good idea. But for now, we want to use the social links and GitHub discussions as the medium for contacting us rather than a 'Contact Us' page. So, we're closing this issue.
