### ISSUE TITLE
Feature: Add Dark mode & Light mode to all pages

### ISSUE THREAD

**Issue by Surajit0573** [Sriparno08/Openpedia#301]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [X] Codebase
- [X] User Interface
- [X] Feature Request

## Description

Currently there is Dark mode only at home page, I want to add Dark mode & Light mode to all pages. (JWOC)
- Introduction to Open Source page
![image](https://github.com/Sriparno08/Openpedia/assets/111490250/9262cd5d-bff7-4699-8b5d-25e3c11c9978)
- Contributing to Open Source page
![image](https://github.com/Sriparno08/Openpedia/assets/111490250/20b29feb-7d11-4d73-98ec-b1843d17f982)
- Beginner-Friendly Repos page
![image](https://github.com/Sriparno08/Openpedia/assets/111490250/1c1e7b7e-6461-45d5-af7b-569c4384517a)
- Open source Program page
![image](https://github.com/Sriparno08/Openpedia/assets/111490250/b61c6cb4-3857-405b-9833-14aa8ae4a90f)

**Comment by Sriparno08** [comment]
You're assigned.

**Comment by Sriparno08** [comment]
@Surajit0573 Please submit a PR as soon as possible. Otherwise, you will be unassigned from this issue.

**Comment by Surajit0573** [comment]
I will PR within today.

**Comment by Sriparno08** [comment]
Okay 👍
