### ISSUE TITLE
FEAT: add cookie consent box

### ISSUE THREAD

**Issue by Sneha6003** [Sriparno08/Openpedia#303]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [ ] User Interface
- [X] Feature Request

## Description
I would like to add a cookie consent box for enhancement of user experience.
I would like to work on this issue under JWOC.

**Comment by Sriparno08** [comment]
Good idea. However, it's not quite necessary for this particular website and hence, we don't want to implement it. So, we are closing this one.
