### ISSUE TITLE
Chore: Remove 'FAQ' from Landing Page Navbar

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#306]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [x] Codebase
- [ ] User Interface
- [ ] Feature Request

## Description

We need to remove the 'FAQ' link from the landing page navbar.

<p align="center">
  <img src= "https://github.com/Sriparno08/Openpedia/assets/89148144/7b804fad-06ef-4c4e-9e1f-ea9ee2c00816">
</p>

**Comment by SuvayuN** [comment]
I want to work in this issue under JWOC'24

**Comment by Sriparno08** [comment]
You're assigned.
