### ISSUE TITLE
Chore: Remove 'FAQ' from 'Introduction to Open Source' Page Navbar

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#307]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [x] Codebase
- [ ] User Interface
- [ ] Feature Request

## Description

We need to remove the 'FAQ' link from the 'Introduction to Open Source' page navbar.

<p align="center">
  <img src= "https://github.com/Sriparno08/Openpedia/assets/89148144/4e226137-7d02-48da-813b-0b8b18084a83">
</p>

**Comment by SuvayuN** [comment]
I want to work on this issue under JWOC'24

**Comment by Sriparno08** [comment]
Once your PR for the issue that you're already assigned to gets merged, you will be considered for this issue. If anyone asks to be assigned before your PR is merged, he/she will be assigned to this issue.

**Comment by Sriparno08** [comment]
You're assigned.
