### ISSUE TITLE
Chore: Remove 'FAQ' from 'Learn Git & GitHub' Page Navbar

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#308]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [x] Codebase
- [ ] User Interface
- [ ] Feature Request

## Description

We need to remove the 'FAQ' link from the 'Learn Git & GitHub' page navbar.

<p align="center">
  <img src= "https://github.com/Sriparno08/Openpedia/assets/89148144/b2669cb7-db4c-45d3-a468-99277c52e44d">
</p>

**Comment by SuvayuN** [comment]
I want to work on this project under JWOC'24

**Comment by Sriparno08** [comment]
Once your PR for the issue that you're already assigned to gets merged, you will be considered for this issue. If anyone asks to be assigned before your PR is merged, he/she will be assigned to this issue.

**Comment by Sriparno08** [comment]
You're assigned.
