### ISSUE TITLE
Chore: Remove 'FAQ' from 'Contributing to Open Source' Page Navbar

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#309]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [x] Codebase
- [ ] User Interface
- [ ] Feature Request

## Description

We need to remove the 'FAQ' link from the 'Contributing to Open Source' page navbar.

<p align="center">
  <img src= https://github.com/Sriparno08/Openpedia/assets/89148144/bdc113ac-937e-44d5-bde6-6351b70376d5">
</p>

**Comment by SuvayuN** [comment]
I want to work on this project under JWOC'24

**Comment by Sriparno08** [comment]
Once your PR for the issue that you're already assigned to gets merged, you will be considered for this issue. If anyone asks to be assigned before your PR is merged, he/she will be assigned to this issue.

**Comment by Sneha123-zudo** [comment]
Please assign me this issue under JWOC

**Comment by Sriparno08** [comment]
@Sneha123-zudo You're assigned.
