### ISSUE TITLE
Chore: Remove 'FAQ' from 'Beginner-Friendly Repos' Page Navbar

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#310]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [x] Codebase
- [ ] User Interface
- [ ] Feature Request

## Description

We need to remove the 'FAQ' link from the 'Beginner-Friendly Repos' page navbar.

<p align="center">
  <img src= "https://github.com/Sriparno08/Openpedia/assets/89148144/4e226137-7d02-48da-813b-0b8b18084a83">
</p>

**Comment by SuvayuN** [comment]
I want to work on the issue under JWOC'24

**Comment by Sriparno08** [comment]
You're assigned.
