### ISSUE TITLE
Chore: Remove 'FAQ' from 'Open Source Programs' Page Navbar

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#311]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [x] Codebase
- [ ] User Interface
- [ ] Feature Request

## Description

We need to remove the 'FAQ' link from the 'Open Source Programs' page navbar.

<p align="center">
  <img src= "https://github.com/Sriparno08/Openpedia/assets/89148144/9944c739-ebd4-4b0a-b72f-d13587470a5f">
</p>

**Comment by SuvayuN** [comment]
I want to work on this project under JWOC'24
