### ISSUE TITLE
Chore: Remove 'Home' from 'Introduction to Open Source' Page Navbar

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#313]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [x] Codebase
- [ ] User Interface
- [ ] Feature Request

## Description

We need to remove the 'Home' link from the 'Introduction to Open Source' page navbar.

<p align="center">
  <img src= "https://github.com/Sriparno08/Openpedia/assets/89148144/ee9e1366-ec80-438a-862b-843bdc373400">
</p>

**Comment by SuvayuN** [comment]
I want to work on this issue under JWOC'24

**Comment by Sriparno08** [comment]
You're assigned.
