### ISSUE TITLE
Chore: Remove 'About' from 'Learn Git & GitHub' Page Navbar

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#314]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [x] Codebase
- [ ] User Interface
- [ ] Feature Request

## Description

We need to remove the 'About' link from the 'Learn Git & GitHub' page navbar.

<p align="center">
  <img src= "https://github.com/Sriparno08/Openpedia/assets/89148144/7265b1b9-3130-48a3-8dce-f4e7621652ee">
</p>

**Comment by SuvayuN** [comment]
I want to work on this issue under JWOC'24

**Comment by Sriparno08** [comment]
You're assigned.
