### ISSUE TITLE
Chore: Remove 'Home' from 'Contributing to Open Source' Page Navbar

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#315]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [x] Codebase
- [ ] User Interface
- [ ] Feature Request

## Description

We need to remove the 'Home' link from the Contributing to Open Source' page navbar.

<p align="center">
  <img src= "https://github.com/Sriparno08/Openpedia/assets/89148144/ccf14a27-4e62-425b-8a4b-097ba9cdbe32">
</p>

**Comment by SuvayuN** [comment]
I want to work on this project as a contribution under JWOC'24

**Comment by Sriparno08** [comment]
You're assigned.
