### ISSUE TITLE
Chore: Remove 'Home' from 'Beginner-Friendly Repos' Page Navbar

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#316]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [x] Codebase
- [ ] User Interface
- [ ] Feature Request

## Description

We need to remove the 'Home' link from the 'Beginner-Friendly Repos' page navbar.

<p align="center">
  <img src= "https://github.com/Sriparno08/Openpedia/assets/89148144/ff44cacb-8f22-4e45-b1be-212d73cb7264">
</p>

**Comment by SuvayuN** [comment]
I want to work on this issue as a JWOC'24 contribution
