### ISSUE TITLE
Chore: Remove 'Home' from 'Open Source Programs' Page Navbar

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#317]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [x] Codebase
- [ ] User Interface
- [ ] Feature Request

## Description

We need to remove the 'Home' link from the 'Open Source Programs' page navbar.

<p align="center">
  <img src= "https://github.com/Sriparno08/Openpedia/assets/89148144/ee9e1366-ec80-438a-862b-843bdc373400">
</p>

**Comment by SuvayuN** [comment]
I want to work under this issue as a contribution under JWOC'24

**Comment by Sriparno08** [comment]
Once your PR for the issue that you're already assigned to gets merged, you will be considered for this issue. If anyone asks to be assigned before your PR is merged, he/she will be assigned to this issue.

**Comment by Sriparno08** [comment]
You're assigned.
