### ISSUE TITLE
Chore: Insert 'About' in Landing Page Navbar

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#318]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [x] Codebase
- [ ] User Interface
- [ ] Feature Request

## Description

We need to insert 'About' under 'Support' in landing page footer that links to the following URL:

> https://openpedia.netlify.app/#about

<p align="center">
  <img src= "https://github.com/Sriparno08/Openpedia/assets/89148144/1bfca96c-97bd-4d64-aac9-ed90dd012786">
</p>

**Comment by AryanPahuja21** [comment]
@Sriparno08 please assign this issue to me under JWOC'24

**Comment by Sriparno08** [comment]
You're assigned.

**Comment by Sriparno08** [comment]
@AryanPahuja21 Please submit a PR as soon as possible. Otherwise, you will be unassigned from this issue.
