### ISSUE TITLE
Add Loading Page with Logo !

### ISSUE THREAD

**Issue by SohanRC** [Sriparno08/Openpedia#332]
## Category

- [X] User Interface
- [X] Feature Request

## Description

Add a loading Page with Logo ! Please assign me under JWOC 2024

**Comment by Sriparno08** [comment]
@SohanRC For now, we don't want to add a loading page to the website. So, we're closing this issue.

**Comment by SohanRC** [comment]
> @SohanRC For now, we don't want to add a loading page to the website. So, we're closing this issue.

ok
