### ISSUE TITLE
Style : Add responsiveness to "Opensource Programs" webpage

### ISSUE THREAD

**Issue by SaranshBangar** [Sriparno08/Openpedia#340]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

## Description

The "Opensource Programs" webpage is not responsive, all the text divs shift to the left when the screen size is shrunk 

![image](https://github.com/Sriparno08/Openpedia/assets/114401238/be8aa5cf-cb16-442f-aac1-5f1993742644)

**Comment by Sriparno08** [comment]
You're assigned.

**Comment by SaranshBangar** [comment]
Solved in PR #341
