### ISSUE TITLE
UI: Change 'Get Started' Border Color in Landing Page Dark Mode

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#344]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

## Description

We need to change the border color of 'Get Started' in landing page dark mode to 'white'.

**Comment by ramith-kulal** [comment]
would work on this under jwoc

**Comment by Sriparno08** [comment]
You're assigned.
