### ISSUE TITLE
UI: Change 'More' Border Color in Landing Page Dark Mode

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#345]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

## Description

We need to change the border color of 'More' in landing page dark mode to 'white'.

**Comment by Bibek478** [comment]
I would like to work on this could you assign me this under jwoc24.
And which border color would like to give ?

**Comment by Sriparno08** [comment]
You're assigned.

The 'More' border color in the landing page should be 'white' in dark mode.

**Comment by Bibek478** [comment]
What name should I give to the new branch ?
