### ISSUE TITLE
Chore: Add Link to 'Documentation' in Landing Page Footer

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#347]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [x] Codebase
- [ ] User Interface
- [ ] Feature Request

## Description

We need to add a link to 'Documentation' in landing page footer.

Link: https://github.com/Sriparno08/Openpedia

**Comment by ramith-kulal** [comment]
can i do thins under jwoc

**Comment by Sriparno08** [comment]
You're assigned.
