### ISSUE TITLE
UI: Separate Resources Under 'Articles' in 'Contributing to Open Source' Page

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#350]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

## Description

We need to separate the resources under 'Articles' in 'Contributing to Open Source' page by making them exist in separate boxes. It can look like this:

<p align="center">
  <img src="https://github.com/Sriparno08/Openpedia/assets/89148144/3df0d084-9ec2-4723-a6a4-93abf4d39c10">
</p>

**Comment by Sneha123-zudo** [comment]
Please assign me this issue under JWOC'24
