### ISSUE TITLE
Improve the UI of introduction to open source page and make it responsive 

### ISSUE THREAD

**Issue by Sneha123-zudo** [Sriparno08/Openpedia#366]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

## Description

I want to improve the UI of introduction to open source page as it is not looking good now and I will also make the page responsive. I will fix all these, please assign me this issue under JWOC '24

**Comment by Sriparno08** [comment]
You're assigned.
