### ISSUE TITLE
Develop Responsive and Interactive Contact Us Form 

### ISSUE THREAD

**Issue by Wadgaonkarprathameshdeepak** [Sriparno08/Openpedia#374]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [ ] User Interface
- [x] Feature Request

## Description

I will create the contact us form by creating a responsive design that seamlessly adjusts to different screen sizes and interactive user interfaces.

![Uploading Screenshot 2024-02-20 113941.png…]()

**Comment by Sriparno08** [comment]
Nice idea, but currently we want to stick to GitHub Discussions and social platforms for all types of contact and feedback. So, we're closing this one.

**Comment by Wadgaonkarprathameshdeepak** [comment]
Ok, thanks for the reply.
*Thanks, *
