### ISSUE TITLE
Feat : Migration from CSS to Tailwind

### ISSUE THREAD

**Issue by Piyush-linux** [Sriparno08/Openpedia#375]
## Category

- [x] User Interface

## Description

- This Project uses plain CSS
- we need to migrate css to tailwind 
- low code base gives low maintenance

## Work

- [x] I'm ready to work on this issue !

> If any query plz ask !

**Comment by Sriparno08** [comment]
Good suggestion, Piyush. But for now, we want to keep the vanilla CSS codebase for this project. So, we're closing this one.
