### ISSUE TITLE
Chore: Fix 'Introduction to Open Source' Link in 'Categories' Section

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#378]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [x] Codebase
- [ ] User Interface
- [ ] Feature Request

## Description

We need to fix a broken link in the 'Categories' section of the landing page that heads to the 'Introduction to Open Source' page.

Step 1: Go to `client/index.html`
Step 2: Find the following link under `<section class="categories">...</section>`

```
<a href="./Introduction-opensource/index.html" class="category-link">More</a>
```

Step 3: Change it to

```
<a href="./pages/introduction-to-open-source/index.html" class="category-link">More</a>
```

**Comment by AmirKarma** [comment]
@Sriparno08 could you assign this issue to me?

**Comment by Sriparno08** [comment]
Sure. You're assigned, @AmirKarma!
