### ISSUE TITLE
Chore: Fix 'Learn Git & GitHub' Link in 'Categories' Section

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#379]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [x] Codebase
- [ ] User Interface
- [ ] Feature Request

## Description

We need to fix a broken link in the 'Categories' section of the landing page that heads to the 'Learn Git & GitHub' page.

Step 1: Go to `client/index.html`
Step 2: Find the following link under `<section class="categories">...</section>`

```
<a href="./git/" class="category-link">More</a>
```

Step 3: Change it to

```
<a href="./pages/learn-git-and-github/index.html" class="category-link">More</a>
```

**Comment by AmirKarma** [comment]
@Sriparno08 Can I have this issue?

**Comment by Sriparno08** [comment]
Sure. You're assigned, @AmirKarma!
