### ISSUE TITLE
Chore: Fix 'Contributing to Open Source' Link in 'Categories' Section

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#380]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [x] Codebase
- [ ] User Interface
- [ ] Feature Request

## Description

We need to fix a broken link in the 'Categories' section of the landing page that heads to the 'Contributing to Open Source' page.

Step 1: Go to `client/index.html`
Step 2: Find the following link under `<section class="categories">...</section>`

```
<a href="./Contributing to Opensource/index.html" class="category-link">More</a>
```

Step 3: Change it to

```
<a href="./pages/contributing-to-open-source/index.html" class="category-link">More</a>
```

**Comment by Akchhya** [comment]
I would like to work on this issue and enter to the world of open source , Hope I'll !!

**Comment by Sriparno08** [comment]
Surely, @Akchhya! You're assigned 👍
