### ISSUE TITLE
Chore: Fix 'Introduction to Open Source' Link in Landing Page Footer

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#382]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [x] Codebase
- [ ] User Interface
- [ ] Feature Request

## Description

We need to fix a broken link in the landing page footer that heads to the 'Introduction to Open Source' page.

Step 1: Go to `client/components/footer.js`
Step 2: Find the following link under `<div class="col">...</div>`

```
<a href="./Introduction-opensource/index.html" class="footer-links">Introduction to Open Source</a>
```

Step 3: Change it to

```
<a href="./pages/introduction-to-open-source/index.html" class="footer-links">Introduction to Open Source</a>
```

**Comment by pratham2402** [comment]
Hey! I can solve this issue. Can you assign it to me?

**Comment by Sriparno08** [comment]
Sure. You're assigned!
