### ISSUE TITLE
Chore: Fix 'Learn Git & GitHub' Link in Landing Page Footer

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#383]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [x] Codebase
- [ ] User Interface
- [ ] Feature Request

## Description

We need to fix a broken link in the landing page footer that heads to the 'Learn Git & GitHub' page.

Step 1: Go to `client/components/footer.js`
Step 2: Find the following link under `<div class="col">...</div>`

```
<a href="./git/index.html" class="footer-links">Learn Git & GitHub</a>
```

Step 3: Change it to

```
<a href="./pages/learn-git-and-github/index.html" class="footer-links">Learn Git & GitHub</a>
```

**Comment by GuerkanD** [comment]
Hey, I am a first timer. Can I take this issue?
