### ISSUE TITLE
Chore: Fix 'Beginner-Friendly Repos' Link in Landing Page Footer

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#385]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [x] Codebase
- [ ] User Interface
- [ ] Feature Request

## Description

We need to fix a broken link in the landing page footer that heads to the 'Beginner-Friendly Repos' page.

Step 1: Go to `client/components/footer.js`
Step 2: Find the following link under `<div class="col">...</div>`

```
<a href="./beginner-friendly-repo/index.html" class="footer-links">Beginner-Friendly Repos</a>
```

Step 3: Change it to

```
<a href="./pages/beginner-friendly-repos/index.html" class="footer-links">Beginner-Friendly Repos</a>
```

**Comment by auroOra3** [comment]
Hey I could do this one as well :-)

**Comment by Sriparno08** [comment]
Go on, @auroOra3!

**Comment by Sriparno08** [comment]
Hey @auroOra3, are you still working on this issue? If you are, please open a PR!
