### ISSUE TITLE
Chore: Fix 'Open Source Programs' Link in Landing Page Footer

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#386]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [x] Codebase
- [ ] User Interface
- [ ] Feature Request

## Description

We need to fix a broken link in the landing page footer that heads to the 'Open Source Programs' page.

Step 1: Go to `client/components/footer.js`
Step 2: Find the following link under `<div class="col">...</div>`

```
<a href="./opensource_programs/index.html" class="footer-links">Open Source Programs</a>
```

Step 3: Change it to

```
<a href="./pages/open-source-programs/index.html" class="footer-links">Open Source Programs</a>
```

**Comment by MrVioz** [comment]
Hey Sriparno, is it possible to work on this issue? (:

**Comment by Sriparno08** [comment]
Sure. You're assigned, @MrVioz!
