### ISSUE TITLE
Chore: Fix SVG Link in 'Introduction to Open Source' Page

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#391]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [x] Codebase
- [ ] User Interface
- [ ] Feature Request

## Description

We need to fix a broken SVG link in the 'Introduction to Open Source' page.

Step 1: Go to `client/pages/introduction-to-open-source/index.html`
Step 2: Find the following link under `<head>...</head>`

```
<link rel="icon" href="./assets/short-logo.svg">
```

Step 3: Change it to

```
<link rel="icon" href="../../assets/short-logo.jpg">
```

**Comment by Gilbertoson** [comment]
Hi, I would like to work on this issue, can you assign it to me?

**Comment by Sriparno08** [comment]
You're assigned, @Gilbertoson!
