### ISSUE TITLE
Chore: Fix SVG Link in 'Learn Git & GitHub' Page

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#392]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [x] Codebase
- [ ] User Interface
- [ ] Feature Request

## Description

We need to fix a broken SVG link in the 'Learn Git & GitHub' page.

Step 1: Go to `client/pages/learn-git-and-github/index.html`
Step 2: Find the following link under `<head>...</head>`

```
<link rel="icon" href="./assets/short-logo.svg">
```

Step 3: Change it to

```
<link rel="icon" href="../../assets/short-logo.svg">
```

**Comment by RahulSingh9131** [comment]
Assign me this issue , I will fix this

**Comment by Sriparno08** [comment]
You're assigned, @RahulSingh9131!
