### ISSUE TITLE
Chore: Fix SVG Link in 'Contributing to Open Source' Page

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#393]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [x] Codebase
- [ ] User Interface
- [ ] Feature Request

## Description

We need to fix a broken SVG link in the 'Contributing to Open Source' page.

Step 1: Go to `client/pages/contributing-to-open-source/index.html`
Step 2: Find the following link under `<head>...</head>`

```
<link rel="icon" href="./assets/short-logo.svg">
```

Step 3: Change it to

```
<link rel="icon" href="../../assets/short-logo.jpg">
```

**Comment by RahulSingh9131** [comment]
Assign me this issue

**Comment by Sriparno08** [comment]
Assigned, @RahulSingh9131!
