### ISSUE TITLE
Chore: Fix SVG Link in 'Open Source Programs' Page

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#395]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [x] Codebase
- [ ] User Interface
- [ ] Feature Request

## Description

We need to fix a broken SVG link in the 'Open Source Programs' page.

Step 1: Go to `client/pages/open-source-programs/index.html`
Step 2: Find the following link under `<head>...</head>`

```
<link rel="icon" href="./assets/short-logo.svg">
```

Step 3: Change it to

```
<link rel="icon" href="../../assets/short-logo.jpg">
```

**Comment by auroOra3** [comment]
Hello can I have that issue please? :-)

**Comment by Sriparno08** [comment]
Go ahead, @auroOra3!
