### ISSUE TITLE
Chore: Fix Navbar Logo Link in Landing Page Navbar

### ISSUE THREAD

**Issue by fellalli** [Sriparno08/Openpedia#417]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

## Description

If I click on the logo in the navbar, I expect to be redirected to https://openpedia.netlify.app/.

**Comment by Sriparno08** [comment]
Well Spotted, @fellalli! You're assigned. 👍

You need to make the changes in the `client/components/footer.js` file.

**Comment by fellalli** [comment]
@Sriparno08 I was referring to the navigation bar in the header. I'm not sure if it's necessary for the logo in the footer to be clickable.

**Comment by Sriparno08** [comment]
Got it, @fellalli. Then, you need to make the changes in the `client/components/header.js` file.
