### ISSUE TITLE
Revamp Hero Page Interface: Update Categories Sections and Cards UI

### ISSUE THREAD

**Issue by aswathcm29** [Sriparno08/Openpedia#419]
### Description:
I wish to enhance the user experience on the hero page by revamping the UI for the categories sections and their respective cards. This issue involves updating the design, layout, and applying some modern UI effects to make the hero page more engaging and visually appealing.

### Tasks:
1. Revamp Category Cards:
   - Enhance the visual design of the category cards to make them more attractive.
   - Add hover effects for better interactivity.
   - Update colors, and spacing for a cleaner look for both dark and light modes.

2. Implement UI Effects:
   - Add subtle animations to elements on the hero page to enhance user engagement.
   - Ensure effects are smooth and do not hinder page performance.

### Expected Outcome:
A visually enhanced and user-friendly hero page with updated UI for the categories sections and cards, along with engaging effects that improve the overall user experience.

### Priority:
High

### Deadline:
20/7/2024

**Comment by aswathcm29** [comment]
Hope you'll find this issue and assign it to me

**Comment by Sriparno08** [comment]
Nice suggestions, @aswathcm29! These can all be implemented.

I'm assigning this issue to you!

**Comment by aswathcm29** [comment]
Yup Thanks ! I'll make it done as soon as possible and raise the PR @Sriparno08 !

**Comment by Sriparno08** [comment]
Great, @aswathcm29!
