### ISSUE TITLE
[UI] Add Hover Effect to 'Documentation' in Landing Page Footer

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#420]
## Category

- [ ] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [x] User Interface
- [ ] Feature Addition

## Description

We need to add a hover effect to 'Documentation' in the landing page footer.

To do this, change the following code in 'client/components/footer.js':

```html
<p>
  <a href="https://github.com/Sriparno08/Openpedia"
      style="text-decoration: none; color: inherit; font-size: 14px;">
      Documentation
  </a>
</p>
```

To:

```html
<p><a href="https://github.com/Sriparno08/Openpedia" class="footer-links">Documentation</a></p>
```

**Comment by Subhraaa** [comment]
hi! @Sriparno08 I am interested to work on this issue

**Comment by Sriparno08** [comment]
Great, @Subhraaa! I'm assigning this issue to you.
