### ISSUE TITLE
[UI] Add Hover Effect to 'About' in Landing Page Footer

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#421]
## Category

- [ ] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [x] User Interface
- [ ] Feature Addition

## Description

We need to add a hover effect to 'About' in the landing page footer.

To do this, change the following code in 'client/components/footer.js':

```html
<a style="font-size: 14px; margin-top: 0.5rem;" href="#about">About</a></p>
```

To:

```html
<p><a href="#about" class="footer-links">About</a></p>
```

**Comment by Mehdi-Messaadi** [comment]
Hi!
I'd like this issue assigned to me, please!

**Comment by Sriparno08** [comment]
Hey @Mehdi-Messaadi, you opened a PR first and then claimed the issue. I don't think this is the correct approach. Please start working on an issue after getting assigned to it.

Hey @Yashop181, please start working on an issue after getting assigned to it.

Since both the contributors made the PRs without getting assigned, I'll go for the one which was created first.

Hence, we're taking your PR into consideration for this time, @Mehdi-Messaadi.

@Yashop181, your PR is not being considered for this time unfortunately. Please go to the 'Issues' tab and claim an issue that interests you. Remember, the issues are assigned on a first-come-first-serve basis.
