### ISSUE TITLE
[Chore] Remove Attributes for 'Support' in Landing Page Footer

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#423]
## Category

- [ ] Resource Addition
- [ ] Documentation
- [x] Codebase
- [ ] User Interface
- [ ] Feature Addition

## Description

We need to remove the attributes for 'Support' in the landing page footer.

To do this, remove the `id` and `style` attributes from the following code in 'client/components/footer.js':

```html
<h3 id="Support" style="font-size: 15px;">Support</h3>
```

**Comment by rnavaneeth992** [comment]
@Sriparno08 Can you assign me this

**Comment by Sriparno08** [comment]
Sure. You're assigned. 👍

**Comment by rnavaneeth992** [comment]
@Sriparno08 can you merge it
