### ISSUE TITLE
[Chore] Remove Attributes for 'Categories' in Landing Page Footer

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#424]
## Category

- [ ] Resource Addition
- [ ] Documentation
- [x] Codebase
- [ ] User Interface
- [ ] Feature Addition

## Description

We need to remove the attributes for 'Categories' in the landing page footer.

To do this, remove the `id` and `style` attributes from the following code in 'client/components/footer.js':

```html
<h3 id="Solutions" style="font-size: 15px;">Categories</h3>
```

**Comment by srodif** [comment]
Hello! May I take this?

**Comment by Sriparno08** [comment]
Sure, @srodif! You're assigned. 👍

**Comment by rnavaneeth992** [comment]
@Sriparno08 Can you assign me this

**Comment by Sriparno08** [comment]
Hey @rnavaneeth992, another contributor is already assigned to this issue.
