### ISSUE TITLE
[Chore] Insert Data Dynamically Using JS in 'Learn Git & GitHub' Page

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#428]
## Category

- [ ] Resource Addition
- [ ] Documentation
- [x] Codebase
- [ ] User Interface
- [ ] Feature Addition

## Description

We need to insert data dynamically using JavaScript in the 'Learn Git & GitHub' Page.

Guidelines:

- Ensure that the JavaScript file is named 'app.js'
- The file needs to be created in 'client/pages/learn-git-and-github'

**Comment by rnavaneeth992** [comment]
@Sriparno08 Can you assign me this task

**Comment by Sriparno08** [comment]
Sure, @rnavaneeth992. You're assigned! 👍
