### ISSUE TITLE
[Chore] Insert Data Dynamically Using JS in 'Contributing to Open Source' Page

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#429]
## Category

- [ ] Resource Addition
- [ ] Documentation
- [x] Codebase
- [ ] User Interface
- [ ] Feature Addition

## Description

We need to insert data dynamically using JavaScript in the 'Contributing to Open Source' Page.

Guidelines:

- Ensure that the JavaScript file is named 'app.js'
- The file needs to be created in 'client/pages/contributing-to-open-source'

**Comment by rnavaneeth992** [comment]
@Sriparno08 Can you assign me this

**Comment by Sriparno08** [comment]
Sure. You're assigned. 👍
