### ISSUE TITLE
Improving the Resources section UI : Update Resources Section of "Introduction to open source" page

### ISSUE THREAD

**Issue by tharagaramanbalaji** [Sriparno08/Openpedia#434]
Description:
I wish to change to user interface of the resources section of mentioned webpage to make it more interactive and aesthetically pleasing for the user eyes ,This issue will include changes being made in the design , layout and the webpage should become pleasing and not difficult to understand 

Tasks :
- [ ] Increase the attractiveness of the resources section 
- [ ] Changing the layout of the resources to a better position 
- [ ] Make alterations with keeping night and day mode in mind 
- [ ] Adding subtle animations to improve the UI 

Expected Outcome :
The resources section will have an enhanced and visually appealing design with a user-friendly layout. Subtle animations and support for both night and day modes will provide an improved and engaging user experience.

Priority and Deadline :
High & 28/7/2024

**Comment by tharagaramanbalaji** [comment]
I hope this issue reaches you and it would be great if assign this to me

**Comment by Sriparno08** [comment]
Hey @tharagaramanbalaji, sounds nice! I'm assigning this to you. 👍
