### ISSUE TITLE
[UI] Wrapping the cards displayed in beginner friendly repos inside a grid

### ISSUE THREAD

**Issue by Salai-Kowshikan** [Sriparno08/Openpedia#439]
## Category

- [ ] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [x] User Interface
- [ ] Feature Addition

## Description

Right now, the cards in the beginner friendly repositories page are being rendered as full width cards which is not good UX. The Ideal reading width is usually between 40-70 characters per line and hence it would be better to wrap it inside a grid and render multiple cards in a row depending on the width dynamically.

**Comment by Salai-Kowshikan** [comment]
What I am suggesting is something similar to cards in other pages, hope you consider this and assign me to this issue

**Comment by Sriparno08** [comment]
Good idea, @Salai-Kowshikan! I'm assigning this to you. 👍
