### ISSUE TITLE
[Resource] Add GitHub Docs

### ISSUE THREAD

**Issue by Vignesh025** [Sriparno08/Openpedia#442]
## Category

- [x ] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [ ] User Interface
- [ ] Feature Addition

## Description
Name: GitHub Docs
Link: https://docs.github.com/en/get-started/start-your-journey/hello-world

**Comment by Vignesh025** [comment]
I want to add a resource to the Learn Git and GitHub page.

**Comment by Sriparno08** [comment]
Sure, @Vignesh025. You're assigned! 👍
