### ISSUE TITLE
[UI Enhancement] Improvement on the About and Contribution section in landing page

### ISSUE THREAD

**Issue by Cibiyanna26** [Sriparno08/Openpedia#446]
## Category

- [ ] Resource Addition
- [ ] Documentation
- [x] Codebase
- [ ] User Interface
- [ ] Feature Addition

## Description

I would like to improve the UI part on landing page where the user is asked, are you willing to contribute or you want to know about us ( star and sponsor ) . Improving these two sections will enhance the user experience and will motivate the contributors to explore more about the project.

**Plans**

1. Implementation of animations
2. Improving Borders
3. zigzag cards
4. Gradients Colors

**Bugs**

It seems the dark mode switching is properly working only for the landing page and not for site sections.

**Comment by Cibiyanna26** [comment]
Could you please assign this issue to me? I am eager to start working on it and contribute to the project. Contributor from CSSOC.

**Comment by Sriparno08** [comment]
Sounds good, @Cibiyanna26. You're assigned!

**Comment by Cibiyanna26** [comment]
Thanks @Sriparno08.
