### ISSUE TITLE
Why not adding Flutter as a beginner friendly repo as a cross wroking platform?

### ISSUE THREAD

**Issue by surya-moorthy** [Sriparno08/Openpedia#448]
## Category

- [x] Resource Addition
- [x] Documentation
- [x ] Codebase
- [x] User Interface
- [x] Feature Addition

## Description
I would like to add a section as  cross platform app development in beginner friendly repos , and 
I would like to add flutter as cross platform app development . as react-native is also we can also add one of the cross platform to use , so this makes a best choice to contributors/students for app development , I would like this issue and work on it if you feel that it is a good choice and assign me for this

Name:flutter docs
Link: https://github.com/flutter
-->

**Comment by Sriparno08** [comment]
Sounds good, @surya-moorthy. You're assigned!

**Comment by surya-moorthy** [comment]
thank you for assigning owrk on it soon
