### ISSUE TITLE
[Bug] Footer links not working properly

### ISSUE THREAD

**Issue by nipunh** [Sriparno08/Openpedia#455]
## Category

- [ ] Resource Addition
- [ ] Documentation
- [x] Codebase
- [ ] User Interface
- [ ] Feature Addition

## Description
The footer links are not working as expected. Navigating from the homepage footer works fine but from any other categories page, it will show a page not found.
For example, go to Introduction to Open Source, and then from the footer go to Learn Git & GitHub.

<img width="1512" alt="Screenshot 2024-08-04 at 11 29 46 AM" src="https://github.com/user-attachments/assets/950faf18-ca2d-4e91-b017-a3df5e8ae885">
<img width="1512" alt="Screenshot 2024-08-04 at 11 29 53 AM" src="https://github.com/user-attachments/assets/6d90b536-d7f6-4d9b-8ea2-3e1f96c8ccca">

**Comment by nipunh** [comment]
@Sriparno08 I will take this.

**Comment by Sriparno08** [comment]
Good spot, @nipunh. You're assigned!
