### ISSUE TITLE
[UI] Enhance UI in 'Introduction to Open Source' Page

### ISSUE THREAD

**Issue by shaileshkaliya** [Sriparno08/Openpedia#460]
# UI Enhancements Proposal

## Category

- [x] User Interface

## Description

I am proposing UI enhancements for the following pages:

1. **Introduction to Open Source Page**: 
   - Improved visual elements for better readability and user engagement.

2. **Learn Git and GitHub Page**: 
   - Enhanced navigation and layout to make content more accessible.

3. **Contributing to Open Source Page**: 
   - Refined the user interface for smoother interaction and guidance.

4. **Beginner-Friendly Repositories Page**: 
   - Updated the UI to ensure clarity and ease of use for newcomers.

These changes aim to improve the overall user experience by making the pages more visually appealing and easier to navigate.

---

**Comment by Sriparno08** [comment]
Sounds good, @shaileshkaliya!

Let's go one-by-one. For this issue, you can go for the 'Introduction to Open Source' page. Then, you can open separate issues for each page that you suggested.

I'm assigning this to you.

**Comment by shaileshkaliya** [comment]
Yeah okay sure

**Comment by Sriparno08** [comment]
Hey @shaileshkaliya, are you still working on this issue? If you are, please open a PR so it can be reviewed.

**Comment by shaileshkaliya** [comment]
Yess I'm working on it. Was busy in something will open the pr
