### ISSUE TITLE
[UI] Auto Slideshow

### ISSUE THREAD

**Issue by rnavaneeth992** [Sriparno08/Openpedia#461]
## Category

- [ ] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [x] User Interface
- [ ] Feature Addition

## Description

https://openpedia.netlify.app/pages/introduction-to-open-source/ -> 
![image](https://github.com/user-attachments/assets/4384175d-e9f9-4fda-a7fa-609414681e1b)

Add Auto Slideshow

**Comment by rnavaneeth992** [comment]
@Sriparno08 Can assign me this issue

**Comment by Sriparno08** [comment]
Hey @rnavaneeth992, it's a good idea. However, in this particular case, my preference is that the resources stay static and the user slides it manually if required rather than a slideshow. So, I'm closing this one.
