### ISSUE TITLE
[UI] Dark mode for Learn Git and GitHub Page

### ISSUE THREAD

**Issue by rnavaneeth992** [Sriparno08/Openpedia#462]
## Category

- [ ] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [x] User Interface
- [ ] Feature Addition

## Description

Dark mode is not working in Learn Git and GitHub Page

I will add that

**Comment by rnavaneeth992** [comment]
@Sriparno08 Can you assign me this issue

**Comment by Sriparno08** [comment]
Sounds good, @rnavaneeth992. I'm assigning this to you.
