### ISSUE TITLE
[Docs] Updated the GitHub- Get Started resource in the ReadMe File. 

### ISSUE THREAD

**Issue by Vignesh025** [Sriparno08/Openpedia#464]
## Category

- [ ] Resource Addition
- [x] Documentation
- [ ] Codebase
- [ ] User Interface
- [ ] Feature Addition

## Description

Updated the GitHub - Get Started resource to the Learn Git and GitHub section in the ReadMe file.

Before:

![image](https://github.com/user-attachments/assets/374d17bf-a2b7-4a3c-af5d-cdc4ab2699fe)

After :

![image](https://github.com/user-attachments/assets/ef94d6ed-30f7-443e-9202-70d8a144e0f5)

**Comment by Sriparno08** [comment]
Good one, @Vignesh025. I'm assigning this to you.
