### ISSUE TITLE
[Docs] Updated the flutter repository in the Beginner Friendly Repositories Section in README.

### ISSUE THREAD

**Issue by Vignesh025** [Sriparno08/Openpedia#470]
## Category

- [ ] Resource Addition
- [x] Documentation
- [ ] Codebase
- [ ] User Interface
- [ ] Feature Addition

## Description

Updated the flutter repository in the Beginner Friendly Repositories Section in README.
Before: 
![image](https://github.com/user-attachments/assets/c475d926-b5f6-4590-b189-6111ebad4ed3)
After:
![image](https://github.com/user-attachments/assets/11a00964-7b28-47f3-a7a6-6f024ef8bf98)

**Comment by Sriparno08** [comment]
Go ahead, @Vignesh025! I'm assigning this to you.
