### ISSUE TITLE
[UI] Dark mode for Contributing to Open Source Page

### ISSUE THREAD

**Issue by rnavaneeth992** [Sriparno08/Openpedia#474]
## Category

- [ ] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [x] User Interface
- [ ] Feature Addition

**Comment by Sriparno08** [comment]
Sure, @rnavaneeth992. You're assigned!

**Comment by prashantrai-30** [comment]
Hey @Sriparno08 ,I have a potential solution for this, can you assign it to me.

**Comment by Sriparno08** [comment]
Hey @prashantrai-30, this issue has been closed as the changes from the assignee has already been merged.
