### ISSUE TITLE
[UI] Make Contributing to Open Source Page Responsive

### ISSUE THREAD

**Issue by rnavaneeth992** [Sriparno08/Openpedia#475]
## Category

- [ ] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [x] User Interface
- [ ] Feature Addition

## Description

![image](https://github.com/user-attachments/assets/8e61ed22-aea2-4f08-97b8-7bfe53a48f9d)

**Comment by rnavaneeth992** [comment]
@Sriparno08 Can you assign me this issue

**Comment by Sriparno08** [comment]
Sure, @rnavaneeth992. You're assigned!
