### ISSUE TITLE
[UI] Make About and Contribute Section Responsive

### ISSUE THREAD

**Issue by rnavaneeth992** [Sriparno08/Openpedia#477]
## Category

- [ ] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [x] User Interface
- [ ] Feature Addition

## Description

![image](https://github.com/user-attachments/assets/e8f7d4ff-ffe7-40af-b733-d9348c8ef772)

**Comment by rnavaneeth992** [comment]
@Sriparno08 Can you assign me this issue

**Comment by Sriparno08** [comment]
Sure, @rnavaneeth992. You're assigned!
