### ISSUE TITLE
[UI] Make 'Open Source Programs' Page Responsive

### ISSUE THREAD

**Issue by rnavaneeth992** [Sriparno08/Openpedia#483]
## Category

- [ ] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [x] User Interface
- [ ] Feature Addition

## Description

![image](https://github.com/user-attachments/assets/488fd7e1-2a2c-4315-9a85-7a48c0281367)

**Comment by rnavaneeth992** [comment]
@Sriparno08 Can you assign me this issue

**Comment by Sriparno08** [comment]
Sure, @rnavaneeth992. You're assigned!
