### ISSUE TITLE
[UI] Make Introduction to Open Source Page Responsive

### ISSUE THREAD

**Issue by rnavaneeth992** [Sriparno08/Openpedia#484]
## Category

- [ ] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [x] User Interface
- [ ] Feature Addition

## Description

![image](https://github.com/user-attachments/assets/e3bd900d-72c2-4b82-8b30-080b12051938)

**Comment by rnavaneeth992** [comment]
@Sriparno08 Can you assign me this issue

**Comment by Sriparno08** [comment]
Sure, @rnavaneeth992. You're assigned!
