### ISSUE TITLE
[UI] Dark mode for Introduction to Open Source Page

### ISSUE THREAD

**Issue by rnavaneeth992** [Sriparno08/Openpedia#495]
## Category

- [ ] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [x] User Interface
- [ ] Feature Addition

**Comment by rnavaneeth992** [comment]
@Sriparno08 Can you assign me this issue

**Comment by Sriparno08** [comment]
Sure, @rnavaneeth992. You're assigned!
