### ISSUE TITLE
[Resource] Add 'What Is Open Source Software and How Does It Work?' to Documentation

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#509]
## Category

- [x] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [ ] User Interface
- [ ] Feature Addition

## Description

Category: Introduction to Open Source
Name: What Is Open Source Software and How Does It Work?
Publisher: Black Duck
Link: https://www.blackduck.com/glossary/what-is-open-source-software.html

**Comment by Elaa257** [comment]
Hello, I would like to contribute to your project. :)
Could you describe more detailed what needs to be done for this issue?

**Comment by Elaa257** [comment]
Also, I noticed that some parts of your website are not displayed correctly in dark mode, e.g. the cards on the homepage are not highlighted when hovered, like they do in light mode. Plus, the slider navigation on the page "Indrotuction to Open Source" does not look alright, I added a picture for more details. I would be happy to help you on this :)  
![image](https://github.com/user-attachments/assets/f4de7b9e-a045-415e-a9c2-e21c3039279c)

**Comment by Sriparno08** [comment]
Sure, @Elaa257!

Firstly, you have to insert the specified resource under the given category in README.md for this issue.

Secondly, the hover animation on the cards on the homepage are kept that way as we couldn't find a suitable color to put in there, like we do in light mode.

Thirdly, you're right about the slider navigation and you can surely help us with that.

Lastly, I'm assigning this issue to you!

Note: For this issue, please add the specified resource in README.md only. Then, for each modification like the slider navigation, just open a separate issue and I'll assign them to you.

**Comment by Elaa257** [comment]
@Sriparno08 Thank you for your fast reply! I will start working on this :)
