### ISSUE TITLE
[Resource] Add 'Open-Source Software: An Introduction' to README

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#510]
## Category

- [x] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [ ] User Interface
- [ ] Feature Addition

## Description

Category: Introduction to Open Source
Name: Open-Source Software: An Introduction
Publisher: Open Access Government
Link: https://www.openaccessgovernment.org/open-source-software-an-introduction/140466/

**Comment by Bishal-35** [comment]
I would like to work on it under GSSoC'24 extd and Hacktoberfest 2024

**Comment by Sriparno08** [comment]
Hey @Bishal-35, this repository is not participating in GSSoC '24 Extended, but it does in Hacktoberfest 2024.

Nevertheless, I'm assigning this to you.

**Comment by Bishal-35** [comment]
Thankyou @Sriparno08 for assigning
