### ISSUE TITLE
[Resource] Add 'Open Source Software Overview' to README

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#511]
## Category

- [x] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [ ] User Interface
- [ ] Feature Addition

## Description

Category: Introduction to Open Source
Name: Open Source Software Overview
Publisher: CMS
Link: https://www.cms.gov/tra/Application_Development/AD_0210_Open_Source_Overview.htm

**Comment by Bishal-35** [comment]
I would like to work on it under Hacktoberfest'24. Please assign me.

**Comment by Sriparno08** [comment]
You're assigned, @Bishal-35.

**Comment by Bishal-35** [comment]
@Sriparno08 The link isn't working please check and update it.

**Comment by Sriparno08** [comment]
Good spot, @Bishal-35. It looks like the link doesn't work anymore and it also doesn't redirect us to another working link. So, I guess we'll have to close this issue for now.
