### ISSUE TITLE
[Resource] Add 'The Ultimate Guide to Open-Source Software Development' to README

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#512]
## Category

- [x] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [ ] User Interface
- [ ] Feature Addition

## Description

Category: Introduction to Open Source
Name: The Ultimate Guide to Open-Source Software Development
Publisher: LicenseSpring
Link: https://licensespring.com/blog/glossary/open-source-software/

**Comment by Bishal-35** [comment]
I would like to work on it under Hacktoberfest'24. Please assign me.

**Comment by mahirabidi12** [comment]
I would like to contribute towards your website . Please assign me this issue under hacktoberfest labels.

**Comment by Sriparno08** [comment]
Hey @Bishal-35, since you're already assigned to a handful of issues, we can give the other contributor a chance to work on this issue. This way, we can promote inclusiveness in the open source community. Are you okay with it?

**Comment by Bishal-35** [comment]
Sure @Sriparno08 you can assign him since it helps to increase contribution in open source community.

**Comment by Sriparno08** [comment]
Great! Thanks, @Bishal-35 👍

Hey @mahirabidi12, I'm assigning this to you.

**Comment by Sriparno08** [comment]
Hey @mahirabidi12, are you still working on this issue? If you are, please open a PR!

Also, please note that if there's no response from your side in a week, you will be unassigned unfortunately.

**Comment by nilaygit-10721** [comment]
please assign to me and  tell me what to do with that repo

**Comment by Sriparno08** [comment]
Hey @nilaygit-10721, you need to add the given resource under the specified category (mentioned in the issue description) in README.md.

I'm assigning this to you.
