### ISSUE TITLE
[Resource] Add 'Open Source Software' to README

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#513]
## Category

- [x] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [ ] User Interface
- [ ] Feature Addition

## Description

Category: Introduction to Open Source
Name: Open Source Software
Publisher: Toppr
Link: https://www.toppr.com/guides/computer-science/computer-fundamentals/open-source-concepts/open-source-software/

**Comment by Bishal-35** [comment]
I would like to work on it under Hacktoberfest'24. Please assign me.

**Comment by Sriparno08** [comment]
You're assigned, @Bishal-35.
