### ISSUE TITLE
[Resource] Add 'What is Open Source Software?' to README

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#514]
## Category

- [x] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [ ] User Interface
- [ ] Feature Addition

## Description

Category: Introduction to Open Source
Name: What is Open Source Software?
Publisher: YoungWonks
Link: https://www.youngwonks.com/blog/What-is-Open-Source-Software

**Comment by Bishal-35** [comment]
I would like to work on it under Hacktoberfest'24. Please assign me.

**Comment by Sriparno08** [comment]
You're assigned, @Bishal-35.
