### ISSUE TITLE
[Resource] Add 'Open-Source Software: An Introduction' to README

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#515]
## Category

- [x] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [ ] User Interface
- [ ] Feature Addition

## Description

Category: Introduction to Open Source
Name: Open-Source Software: An Introduction
Publisher: Idalko
Link: https://idalko.com/open-source-software/

**Comment by Bishal-35** [comment]
I would like to work on it under Hacktoberfest'24. Please assign me.

**Comment by Sriparno08** [comment]
You're assigned, @Bishal-35.
