### ISSUE TITLE
[Resource] Add 'Why Open Source Software and Open Standards?' to README

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#516]
## Category

- [x] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [ ] User Interface
- [ ] Feature Addition

## Description

Category: Introduction to Open Source
Name: Why Open Source Software and Open Standards?
Publisher: Dynatrace
Link: https://www.dynatrace.com/news/blog/open-source-software-and-open-standards/

**Comment by Bishal-35** [comment]
I would like to work on it under Hacktoberfest'24. Please assign me.

**Comment by Sriparno08** [comment]
You're assigned, @Bishal-35.
