### ISSUE TITLE
[Resource] Add 'Introduction to Open Source Software' to README

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#517]
## Category

- [x] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [ ] User Interface
- [ ] Feature Addition

## Description

Category: Introduction to Open Source
Name: Introduction to Open Source Software
Publisher: Cratecode
Link: https://cratecode.com/info/open-source-introduction

**Comment by Bishal-35** [comment]
I would like to work on it under Hacktoberfest'24. Please assign me.

**Comment by Sriparno08** [comment]
You're assigned, @Bishal-35.
