### ISSUE TITLE
[Resource] Add 'An Introduction to Open Source Software' to Documentation

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#518]
## Category

- [x] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [ ] User Interface
- [ ] Feature Addition

## Description

Category: Introduction to Open Source
Name: An Introduction to Open Source Software
Publisher: Logan & Partners
Link: https://www.loganpartners.com/an-introduction-to-open-source-software/

**Comment by Arkachau05** [comment]
Interested

**Comment by Arkachau05** [comment]
Can you explain a bit what to do

**Comment by Sriparno08** [comment]
Sure, @Arkachau05.

You need to add the specified resource under the given category in README.md.
