### ISSUE TITLE
[UI] Adapt the slider navigation in dark mode

### ISSUE THREAD

**Issue by Elaa257** [Sriparno08/Openpedia#519]
## Category

- [ ] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [x] User Interface
- [ ] Feature Addition

## Description

Currently, slider navigations are not displayed correctly in dark mode (view image below). Adjust its style to fix this. 
![image](https://github.com/user-attachments/assets/b9573460-c14b-41c7-b980-47504263def7)

**Comment by Sriparno08** [comment]
Hey @Elaa257, you're assigned!

**Comment by Elaa257** [comment]
Hey @Sriparno08, please have a look if my changes fit your style :)
