### ISSUE TITLE
[UI] Add dark mode on "Contribution to Open Source"

### ISSUE THREAD

**Issue by Elaa257** [Sriparno08/Openpedia#522]
## Category

- [ ] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [x] User Interface
- [ ] Feature Addition

## Description

Currently, the page "Contribution to Open Source" is only avaible in light mode. Add styles for dark mode.

**Comment by Sriparno08** [comment]
Let's do this. I'm assigning this to you.

**Comment by Elaa257** [comment]
@Sriparno08 Thank you, I just created a pull request :)
