### ISSUE TITLE
[Codebase] Fix the state of Dark mode on pages

### ISSUE THREAD

**Issue by sergiozeppo** [Sriparno08/Openpedia#524]
## Category

- [ ] Resource Addition
- [ ] Documentation
- [x] Codebase
- [ ] User Interface
- [ ] Feature Addition

## Description

Hi there, Openpedia team! 
Noticed that state of Dark mode is not saves into LocalStorage. 
![image](https://github.com/user-attachments/assets/e1ea1b22-cff2-4a65-b8dc-7d6a1eb91cd0)

Moreover, there are many errors in browser console. 

![image](https://github.com/user-attachments/assets/58f77e34-f8db-4027-9f51-89f14ed5a478)

It leads to situation Dark mode activated, but on another page is Sun shining again )))  

Assign me, please, to help you fix this errors. 
Thanks in advance! You're all doing a great job!

**Comment by Sriparno08** [comment]
Nice suggestions, @sergiozeppo!

You can go ahead. I'm assigning this to you.
