### ISSUE TITLE
[FEAT] Scrollbar Styles

### ISSUE THREAD

**Issue by MishraTanishq619** [Sriparno08/Openpedia#525]
## Category

- [ ] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [x] User Interface
- [x] Feature Addition

## Description

I think we haven't given customised styles to our scrollbar.
We should custom our scrollbar as per our theme.

I want to work on this myself.
Please assign it to me and add tags for hacktoberfest-2024.

**Comment by Sriparno08** [comment]
Hey @MishraTanishq619, it's a nice suggestion. However, our preference is that we want to keep the default scrollbar for now.

So, we'll have to close this issue unfortunately.
