### ISSUE TITLE
[UI] Fix white gap between body and footer

### ISSUE THREAD

**Issue by Elaa257** [Sriparno08/Openpedia#527]
## Category

- [ ] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [x] User Interface
- [ ] Feature Addition

## Description

I noticed that there is a white gap between the body and the footer on some pages (see picture for reference). I would be happy to fix this!  

Page with white gap:  
![image](https://github.com/user-attachments/assets/bae81b64-ce1e-4f21-adf2-abe0c299d13d)  

Page without white gap:
![image](https://github.com/user-attachments/assets/680f8aa5-bd87-49f0-9f7b-5b2ba004078e)

**Comment by Sriparno08** [comment]
Good spot, @Elaa257. I'm assigning this to you.
