### ISSUE TITLE
[UI] < Fix Responsiveness >

### ISSUE THREAD

**Issue by mohtasheem135** [Sriparno08/Openpedia#531]
## Category

- [ ] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [x] User Interface
- [ ] Feature Addition

## Description
There are issues in few pages in mobile view. In few pages text is hidden by the images and in some pages text is going out of box. We need to fix it. 

Please assign this to me and add the hactoberfest and gssoc-extd label.

**Comment by Sriparno08** [comment]
Hey @mohtasheem135, this repository is not participating in GSSOC '24 Extended, but it is participating in Hacktoberfest 2024.

Nevertheless, you can go ahead. I'm assigning this to you.

**Comment by tharagaramanbalaji** [comment]
Is the issue assigned and working or can I try working on the issue

**Comment by Sriparno08** [comment]
Yes @tharagaramanbalaji, this issue is assigned to another contributor.

**Comment by Sriparno08** [comment]
Hey @mohtasheem135, are you still working on this issue? If you are, please open a PR!

Also, please note that if there's no response from your side in a week, you will be unassigned unfortunately.

**Comment by mohtasheem135** [comment]
Hey @Sriparno08 sorry for being this late actually I was not well (cough & cold) and some office works... 

I'll share the PR as soon as possible... Again I am really very sorry for the delay.

**Comment by Sriparno08** [comment]
No worries, @mohtasheem135. Waiting for your PR!

**Comment by Sriparno08** [comment]
Hey @mohtasheem135, it's been almost a month and there's no PR from your side.

Please note that if there's no PR from your side in the next 2 days, you will be unassigned and this issue will be closed unfortunately.
