### ISSUE TITLE
[UI] Updating the Footer

### ISSUE THREAD

**Issue by mohtasheem135** [Sriparno08/Openpedia#532]
## Category

- [ ] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [x] User Interface
- [ ] Feature Addition

**Comment by Sriparno08** [comment]
Hey @mohtasheem135, please state the changes that you want to make in the footer.

**Comment by mohtasheem135** [comment]
I want category and support in two columns and add the icons in the middle for LinkedIn and GitHub. 

![Screenshot_2024-10-13-01-07-55-723_com android chrome](https://github.com/user-attachments/assets/1da614e5-7780-41ef-9048-07496df69848)

**Comment by Sriparno08** [comment]
Hey @mohtasheem135, you can go ahead with the following structure. The only difference is the number of columns. The below image has 4, but we'll have 2:

![image](https://github.com/user-attachments/assets/4f16e772-49fd-4cbd-99fa-60f11facbc33)

**Comment by krishp007** [comment]
The changes are made in the footer:
1. Changed it from 4 col to 3 col
2. Places social icons below

@Sriparno08 Please check my PR

**Comment by Sriparno08** [comment]
Hey @mohtasheem135, are you still working on this issue? If you are, please open a PR!

Also, please note that if there's no response from your side in a week, you will be unassigned unfortunately.

**Comment by mohtasheem135** [comment]
Hey @Sriparno08 sorry for being this late actually I was not well (cough & cold) and some office works... 

I'll share the PR as soon as possible... Again I am really very sorry for the delay.

**Comment by Sriparno08** [comment]
No worries, @mohtasheem135. Waiting for your PR!

**Comment by Sriparno08** [comment]
Hey @mohtasheem135, it's been almost a month and there's no PR from your side.

Please note that if there's no PR from your side in the next 2 days, you will be unassigned and this issue will be closed unfortunately.
