### ISSUE TITLE
[UI] Fix dark mode on "Beginner-Friendly Repos"

### ISSUE THREAD

**Issue by Elaa257** [Sriparno08/Openpedia#543]
## Category

- [ ] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [x] User Interface
- [ ] Feature Addition

## Description

Hey, I noticed that the cards on the page "Beginner-friendly repos" are very hard to read when the page is in dark mode. I would be happy to fix that!

**Comment by Sriparno08** [comment]
Good catch, @Elaa257!

Go ahead. I'm assigning this to you.
