### ISSUE TITLE
[Feature Addition] <Addition of a Feature Of Rate Us!!>

### ISSUE THREAD

**Issue by SrishtiChamoli** [Sriparno08/Openpedia#544]
## Category

- [ ] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [ ] User Interface
- [x] Feature Addition

## Description

I noticed that the feedback of user is also a necessary component to know what is needed in the website. Hence adding an option of rating using stars for the users will help us to have a nice feedback database. I would love to create a feature as such for your website.

**Comment by SrishtiChamoli** [comment]
This is how the rate us will look like..Ive been working on it since a few days..I'll be glad if I get assigned with this task!
This component appears after 30 seconds of continuous activity on the website.
<img width="926" alt="bug" src="https://github.com/user-attachments/assets/f2d64726-46f0-4a81-8ca3-ca36d94ddd45">

**Comment by SrishtiChamoli** [comment]
This is how the rate us will look like..Ive been working on it since a few days..I'll be glad if I get assigned with this task!
This component appears after 30 seconds of continuous activity on the website.
<img width="945" alt="bus1" src="https://github.com/user-attachments/assets/e0b11205-b963-470a-ad46-c570cfadfcbe">

**Comment by Sriparno08** [comment]
Nice suggestion, @SrishtiChamoli!

Let's do it. I'm assigning this to you.
