### ISSUE TITLE
[UI] Improving the Resources Section in "Learn Git and Github" Page Using Carousel

### ISSUE THREAD

**Issue by tharagaramanbalaji** [Sriparno08/Openpedia#548]
Description : Update the "Resources" section on the Learn Git and GitHub page by adding a carousel similar to the one on the Introduction to Open Source page.

- [ ] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [x] User Interface
- [ ] Feature Addition

Expected Outcome The "Resources" section in "Learn Git and Github" is more interactive and visually engaging, allowing users to browse through resources easily.

Priority & Deadline : High &  21/10/24

**Comment by Sriparno08** [comment]
Good idea, @tharagaramanbalaji. I'm assigning this to you.
