### ISSUE TITLE
[Resource] Fix resource "NJACK Winter of Code" in README

### ISSUE THREAD

**Issue by sergiozeppo** [Sriparno08/Openpedia#550]
## Category

- [x] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [ ] User Interface
- [ ] Feature Addition

## Description

Hi there, Openpedia team!
Noticed that NJACK Winter of Code officially became CodePeak.

Category: Open Source Programs
Name: CodePeak
Link: https://www.codepeak.tech/

Assign me, please to fix it!
Thanks in advance!

**Comment by Sriparno08** [comment]
Nicely observed, @sergiozeppo! Go ahead, you're assigned.
