### ISSUE TITLE
Bug: Unresponsive About and Contribute Cards.

### ISSUE THREAD

**Issue by SrishtiChamoli** [Sriparno08/Openpedia#554]
## Category

- [ ] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [x] User Interface
- [ ] Feature Addition

## Description
This issue in in context with the layout issues with the About and Contribute cards in mobile view, where content and buttons occasionally overlap, creating a cluttered appearance. I would like to improvise these cards and make them responsive on all platforms.
![WhatsApp Image 2024-10-28 at 6 37 29 PM](https://github.com/user-attachments/assets/7d3a0d3d-e932-4ef1-acfa-2445857678bb)

I would love to be assigned on this small issue!

**Comment by Sriparno08** [comment]
Good observation, @SrishtiChamoli. You're assigned!
