### ISSUE TITLE
Add Awesome React

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#59]
## Category

- [ ] Documentation
- [x] Resource Addition

## Description

We need to add Awesome React under 'Beginner-Friendly Repositories'.

Name: Awesome React
Link: https://github.com/enaqx/awesome-react

**Comment by 2div** [comment]
Hi , I want to handle this task.

As per below screenshot , I will add the Awesome React where i draw the red line.

![Capture1](https://github.com/Sriparno08/Openpedia/assets/96177680/dcb26ac7-bd16-4773-a1c1-d2370b7483fd)

**Comment by 2div** [comment]
Thank you for assigning the task to me.
Kindly see my pull request

**Comment by Sriparno08** [comment]
Hey @2div, I've added some suggestions in the PR comments.

Check it out.

**Comment by 2div** [comment]
Hey @Sriparno08  I have updated the PR , kindly review it .
Thank you
