### ISSUE TITLE
Add Balena Docs

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#66]
## Category

- [ ] Documentation
- [x] Resource Addition

## Description

We need to add Balena Docs under 'Beginner-Friendly Repositories'.

Name: Balena Docs
Link: https://github.com/balena-io/docs

**Comment by seasisk** [comment]
Hello, I want to complete this task, apologies if it was poor manners to submit the pull before commenting.

**Comment by Sriparno08** [comment]
It's okay, @seasisk.

Just make sure from the next time that you're assigned to the issue. This way, only you will be working on the issue.

Nevertheless, I'm assigning it to you.
