### ISSUE TITLE
Add React Native

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#71]
## Category

- [ ] Documentation
- [x] Resource Addition

## Description

We need to add React Native under the 'Beginner-Friendly Repositories' section in README.md.

Name: React Native
Link: https://github.com/facebook/react-native

**Comment by HTLA380** [comment]
@Sriparno08 I'd like to work on this issue, could you assign it to me?

**Comment by Sriparno08** [comment]
Sure 👍
