### ISSUE TITLE
Change 'Introduction to Open Source' Description

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#81]
## Category

- [x] Documentation
- [ ] Resource Addition

## Description

We need to change the description under 'Introduction to Open Source' in README.md by replacing the current markdown with the suggested markdown.

Current Markdown:

> Here are some priceless resources that will help answer these questions in detail.

Suggested Markdown:

> Here are some priceless resources that will answer these questions in detail:

**Comment by PraveenShinde3** [comment]
@Sriparno08 can you please assign it to me?

**Comment by Sriparno08** [comment]
Yeah, sure 👍
