### ISSUE TITLE
Change 'Learn Git and GitHub' Description

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#86]
## Category

- [x] Documentation
- [ ] Resource Addition

## Description

We need to change the description under 'Learn Git and GitHub' in README.md by replacing the current markdown with the suggested markdown.

Current Markdown:

> Git and GitHub are two of the most essential tools that you need to master to contribute to open source.
>
> In this section, you will find a list of useful resources that will help you master these essential tools.

Suggested Markdown:

> Git and GitHub are two of the most essential tools that you need to master in order to contribute to open source.
>
> These resources provide a substantial amount of information about these tools, allowing you to get a strong hold of them in a short period of time:

**Comment by PRASUN-SITAULA** [comment]
Hey @Sriparno08, can I work on the issue?

**Comment by Sriparno08** [comment]
Sure 👍
