### ISSUE TITLE
Change 'Contributing to Open Source' Description

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#87]
## Category

- [x] Documentation
- [ ] Resource Addition

## Description

We need to change the description under 'Contributing to Open Source' in README.md by replacing the current markdown with the suggested markdown.

Current Markdown:

> Learning the essentials is only half of the job done as you need to start contributing to open source to get comfortable with the process.
>
> In this section, I have compiled a list of helpful resources that will help you do the same.

Suggested Markdown:

> Learning the contribution workflow is a must in your open source journey.

> This section compiles a list of useful resources that enable you to get started with open source contributions:

**Comment by Kombaiya-MK** [comment]
Can I work on this issue?

**Comment by Sriparno08** [comment]
Sure 👍
