### ISSUE TITLE
Change 'Beginner-Friendly Repos' Description

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#91]
## Category

- [x] Documentation
- [ ] Resource Addition

## Description

We need to change the description under 'Beginner-Friendly Repos' in README.md by replacing the current markdown with the suggested markdown.

Current Markdown:

> Ready to embark on your open source adventure?
>
> These repos offer a welcoming gateway for newcomers, presenting a curated selection of beginner-friendly issues to help you take your first steps into the world of open source:

Suggested Markdown:

> Ready to embark on your open source adventure?
>
> These repos offer a curated selection of beginner-friendly issues that will turn you into a skilled open source contributor:

**Comment by AwaisKhan-Dev** [comment]
@Sriparno08 kindly assign me this issue
