### ISSUE TITLE
Docs: Update 'Open Source Programs' Description

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#93]
## Category

- [x] Documentation
- [ ] Resource Addition

## Description

We need to change the description under 'Open Source Programs' in README.md by replacing the current markdown with the suggested markdown.

Current Markdown:

> There are a lot of open source programs on the internet that allow you to contribute to open source projects.
>
> Here is a list of such initiatives that you can participate in and upskill yourself in open source contributions:

Suggested Markdown:

> There are a lot of open source programs on the internet that enable you to get rewarded for contributing to open source projects.
>
> Here is a list of such initiatives that provide an opportunity for you to upskill in open source contributions and get compensated for your hard work:

**Comment by camilo-zuluaga** [comment]
Hey @Sriparno08, i would like to work on this one

**Comment by Sriparno08** [comment]
Sure 👍
