### ISSUE TITLE
UI: Change Background Color of Landing Page Buttons

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#95]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [x] User Interface

## Description

We need to change the background color of the landing page buttons so that it matches with the theme of the website.

Suggestion: @camilo-zuluaga

![293481068-ef3c2b0d-cd88-4836-ae13-ac8020232393](https://github.com/Sriparno08/Openpedia/assets/89148144/139420d7-c197-4545-a616-583129523036)

**Comment by Sriparno08** [comment]
Hey @camilo-zuluaga, should I assign it to you?

**Comment by camilo-zuluaga** [comment]
Hey, @Sriparno08 
You can assign me this one, and the other one can be solved by someone else 🤝

**Comment by Sriparno08** [comment]
Okay 👍
