### ISSUE TITLE
Docs: Update 'Openpedia' Description in README.md

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#99]
## Category

- [x] Documentation
- [ ] Resource Addition

## Description

We need to change the 'Openpedia' description in README.md by replacing the current markdown with the suggested markdown.

Current Markdown:

> This project strives to guide beginners in getting started with open source by providing a wide range of helpful resources. Anyone can jump right in to contribute to this project and make it a reliable source for finding everything related to open source.

Suggested Markdown:

> Openpedia offers a large amount of useful resources that enable you to become a seasoned open source contributor. If you are aspiring to leave your imprint in the world of open source, then this project is an excellent fit for you.

**Comment by rudransh61** [comment]
Can I do this ?

**Comment by rudransh61** [comment]
Pls assign it to me

**Comment by Sriparno08** [comment]
Sure 👍

**Comment by rudransh61** [comment]
Done
!!
